<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Расписание — {{ $class->name_ru ?? $class->name }}</title>

    <style>
        @page {
            size: A4 landscape;
            margin: 8mm 9mm 13mm;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 9.5px;
            color: #111827;
            margin: 0;
        }

        .meta {
            text-align: center;
            font-size: 10px;
            margin-bottom: 7px;
        }

        table.grid {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed;
            page-break-inside: avoid;
        }

        table.grid th, table.grid td {
            border: 1px solid #d1d5db;
            padding: 4px 3px;
            text-align: center;
            vertical-align: middle;
            line-height: 1.2;
            word-wrap: break-word;
            overflow-wrap: break-word;
        }

        table.grid th {
            background: #111827;
            color: #fff;
            font-weight: bold;
        }

        .lesson-col {
            width: 7%;
        }

        table.grid thead {
            display: table-header-group;
        }

        table.grid tr,
        table.grid th,
        table.grid td {
            page-break-inside: avoid;
        }

        .subject {
            font-weight: bold;
        }

        .teacher {
            color: #4b5563;
            font-size: 8.25px;
        }

        .time {
            color: #6b7280;
            font-size: 8px;
        }

        .empty-cell {
            color: #d1d5db;
        }

        .timetable-footer {
            margin-top: 6px;
            border-top: 1px solid #d1d5db;
            padding-top: 3px;
            color: #6b7280;
            font-size: 8px;
            text-align: center;
        }
    </style>
</head>

<body>

@include('pdf.partials.document-header', ['documentTitle' => 'РАСПИСАНИЕ УРОКОВ', 'schoolSettings' => $schoolSettings ?? null])

<div class="meta">
    Класс: <strong>{{ $class->name_ru ?? $class->name }}</strong>
    @if ($academicYear)
        &nbsp;·&nbsp; Учебный год: <strong>{{ $academicYear->name }}</strong>
    @endif
</div>

<!-- Keep cell content inline for dompdf. In particular, do not combine
     block children in these cells with a fixed-position document footer:
     that layout fragmented this six-row table into seven PDF pages. -->
<table class="grid">
    <colgroup>
        <col class="lesson-col">
        @foreach ($days as $day)
            <col>
        @endforeach
    </colgroup>
    <thead>
        <tr>
            <th class="lesson-col">{{ __('timetable.lesson') }}</th>
            @foreach ($days as $day)
                <th>{{ $day->name }}</th>
            @endforeach
        </tr>
    </thead>

    <tbody>
        @foreach ($periods as $period)
            <tr>
                <td class="lesson-col">
                    {{ $period->number ?? $period->name }}
                    @if ($period->start_time)
                        <br><span class="time">{{ \Illuminate\Support\Str::of($period->start_time)->limit(5, '') }}</span>
                    @endif
                </td>

                @foreach ($days as $day)
                    @php $lesson = $lessons->get($day->id.'-'.$period->id); @endphp
                    <td>
                        @if ($lesson)
                            <span class="subject">{{ $lesson->subject->name_ru }}</span><br><span class="teacher">{{ $lesson->teacher->full_name ?? '' }}</span>
                        @else
                            <span class="empty-cell">—</span>
                        @endif
                    </td>
                @endforeach
            </tr>
        @endforeach
    </tbody>
</table>

<div class="timetable-footer">
    Generated by School ERP
    &nbsp;·&nbsp;
    Учебный год: {{ $academicYear?->name ?? $schoolSettings?->defaultAcademicYear?->name ?? '—' }}
</div>

</body>
</html>
