@extends('layouts.dashboard')
@section('content')
<div class="container-fluid py-4"><div class="d-flex justify-content-between mb-4"><div><h1 class="h3">Новый счёт</h1><div class="text-muted">{{ $student->full_name }}</div></div><a class="btn btn-outline-secondary" href="{{ route('dashboard.students.finance',$student) }}">Назад</a></div>
@if(!$year)<div class="alert alert-warning">У ученика нет активного зачисления.</div>@else
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('dashboard.students.invoices.store',$student) }}" id="modern-invoice-form">@csrf<input type="hidden" name="student_id" value="{{ $student->id }}"><input type="hidden" name="academic_year_id" value="{{ $year->id }}"><input type="hidden" name="initial_payment_amount" value="0">
<div class="card border-0 shadow-sm mb-4"><div class="card-body row g-3"><div class="col-md-4"><label class="form-label">Учебный год</label><input class="form-control" value="{{ $year->name }}" readonly></div><div class="col-md-4"><label class="form-label">Срок оплаты</label><input type="date" name="due_date" class="form-control" value="{{ old('due_date',$year->end_date?->format('Y-m-d')) }}" required></div><div class="col-md-4"><label class="form-label">Примечание</label><input name="notes" class="form-control" value="{{ old('notes') }}"></div></div></div>
<h2 class="h5">Услуги</h2><div class="row g-3">@forelse($fees as $fee)<div class="col-md-6"><div class="card h-100 border-0 shadow-sm"><div class="card-body"><div class="form-check"><input class="form-check-input fee-check" type="checkbox" name="fees[]" value="{{ $fee->id }}" id="fee-{{ $fee->id }}" @checked(in_array($fee->id,old('fees',[])))><label class="form-check-label fw-bold" for="fee-{{ $fee->id }}">{{ $fee->name_ru }}</label></div>@if($fee->prices->count())<label class="form-label mt-2">Вариант тарифа</label><select class="form-select tariff-select" data-fee="{{ $fee->id }}">@foreach($fee->prices as $price)<option value="{{ $loop->index }}" data-price="{{ $price->amount }}" data-grade-group="{{ $price->grade_group }}" data-payment-period="{{ $price->payment_period }}" data-size="{{ $price->size }}" data-item="{{ $price->item }}" data-option-type="{{ $price->option_type }}" data-option-value="{{ $price->option_value }}">{{ collect([$price->grade_group,$price->payment_period,$price->item,$price->size,$price->option_value])->filter()->implode(' · ') ?: 'Основной тариф' }} — {{ $price->amount }} EGP</option>@endforeach</select><div class="mt-2">Цена: <strong class="price-preview">{{ $fee->prices->first()->amount }} EGP</strong></div>@else<div class="mt-2 text-muted">Цена определяется сервером</div>@endif<input type="hidden" name="grade_group[{{ $fee->id }}]"><input type="hidden" name="payment_period[{{ $fee->id }}]"><input type="hidden" name="uniform_size[{{ $fee->id }}]"><input type="hidden" name="uniform_item[{{ $fee->id }}]"><input type="hidden" name="option_type[{{ $fee->id }}]"><input type="hidden" name="option_value[{{ $fee->id }}]"></div></div></div>@empty<div class="alert alert-warning">Активные услуги не настроены.</div>@endforelse</div>
<div class="card border-0 shadow-sm mt-4"><div class="card-body d-flex justify-content-between align-items-center"><div><div class="text-muted">Предварительный итог</div><strong id="invoice-preview-total">0.00 EGP</strong><div class="small text-muted">Окончательная сумма рассчитывается сервером.</div></div><button class="btn btn-primary">Создать счёт</button></div></div></form>@endif</div>
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const update=()=>{let cents=0;document.querySelectorAll('.tariff-select').forEach(select=>{const fee=select.dataset.fee,opt=select.selectedOptions[0],card=select.closest('.card-body');['gradeGroup','paymentPeriod','size','item','optionType','optionValue'].forEach(key=>{const names={gradeGroup:'grade_group',paymentPeriod:'payment_period',size:'uniform_size',item:'uniform_item',optionType:'option_type',optionValue:'option_value'};card.querySelector(`[name="${names[key]}[${fee}]"]`).value=opt.dataset[key]||'';});card.querySelector('.price-preview').textContent=Number(opt.dataset.price||0).toFixed(2)+' EGP';if(card.querySelector('.fee-check').checked)cents+=Math.round(Number(opt.dataset.price||0)*100);});document.getElementById('invoice-preview-total').textContent=(cents/100).toFixed(2)+' EGP';};document.querySelectorAll('.fee-check,.tariff-select').forEach(el=>el.addEventListener('change',update));update();});</script>@endpush
@endsection
