<?php

return [
    'title' => 'Завершение регистрации ученика', 'documents_link' => 'Документы ученика', 'save' => 'Сохранить данные', 'not_provided' => 'Не указано', 'optional' => 'необязательно', 'yes' => 'Да', 'no' => 'Нет', 'unknown' => 'Не указано',
    'sections' => ['readiness' => 'Готовность личного дела', 'personal' => 'Личные данные', 'representatives' => 'Родители и законные представители', 'emergency' => 'Экстренные контакты', 'enrollment' => 'Зачисление и обучение', 'needs' => 'Особые образовательные условия', 'documents' => 'Документы', 'finance' => 'Финансы (только просмотр)', 'completion' => 'Завершение регистрации'],
    'readiness' => ['student' => 'Данные ученика', 'documents' => 'Документы', 'enrollment' => 'Зачисление', 'overall' => 'Общая готовность', 'blocking' => 'Требуется дополнить', 'items' => ['name' => 'Фамилия и имя', 'birth_date' => 'Дата рождения', 'gender' => 'Пол', 'citizenship' => 'Гражданство', 'residential_address' => 'Адрес проживания', 'phone' => 'Телефон', 'contact' => 'Контакт представителя или экстренный контакт', 'academic_year' => 'Учебный год', 'stage' => 'Ступень', 'grade' => 'Класс обучения', 'class' => 'Учебный класс', 'enrollment_date' => 'Дата зачисления'], 'document_items' => ['photo' => 'Фото ученика', 'birth_certificate' => 'Свидетельство о рождении', 'identity' => 'Паспорт или вид на жительство', 'previous_school' => 'Документ из предыдущей школы', 'medical' => 'Медицинский документ']],
    'fields' => ['last_name' => 'Фамилия', 'first_name' => 'Имя', 'patronymic' => 'Отчество', 'gender' => 'Пол', 'male' => 'Мужской', 'female' => 'Женский', 'birth_date' => 'Дата рождения', 'birth_place' => 'Место рождения', 'citizenship' => 'Гражданство', 'citizenship_code' => 'Код страны', 'phone' => 'Телефон', 'email' => 'Email', 'residential_address' => 'Адрес проживания', 'registration_address' => 'Адрес регистрации', 'photo' => 'Фотография ученика', 'snils' => 'СНИЛС', 'inn' => 'ИНН', 'relationship' => 'Кем приходится', 'full_name' => 'ФИО', 'primary_contact' => 'Основной контакт', 'legal_representative' => 'Законный представитель', 'guardianship' => 'Полномочия опекуна', 'address' => 'Адрес', 'notes' => 'Примечания', 'priority' => 'Приоритет', 'admission_context' => 'Контекст зачисления', 'previous_school' => 'Предыдущая школа', 'previous_country' => 'Страна предыдущей школы', 'previous_grade' => 'Предыдущий класс/ступень', 'previous_class' => 'Предыдущая группа/класс', 'previous_notes' => 'Сведения о предыдущем обучении', 'has_ovz' => 'ОВЗ', 'has_disability' => 'Инвалидность', 'requires_adapted_program' => 'Требуется адаптированная программа', 'requires_special_conditions' => 'Требуются специальные условия', 'special_conditions' => 'Специальные условия', 'consent_status' => 'Статус согласия', 'consent_date' => 'Дата согласия'],
    'relationships' => ['father' => 'Отец', 'mother' => 'Мать', 'guardian' => 'Опекун', 'custodian' => 'Попечитель', 'other' => 'Другой'],
    'admission_contexts' => ['initial' => 'Первичное зачисление', 'transfer' => 'Перевод', 'continuation' => 'Продолжение обучения', 're_enrollment' => 'Повторное зачисление', 'other' => 'Другое'],
    'add_representative' => 'Добавить представителя', 'add_emergency' => 'Добавить контакт', 'enrollment_missing' => 'Активное зачисление не найдено.', 'finance_note' => 'Финансы отображаются только для справки и не влияют на готовность личного дела.', 'documents_note' => 'Документы хранятся в существующем защищённом хранилище.', 'submit_review' => 'Отправить на проверку', 'complete' => 'Завершить регистрацию', 'photo_help' => 'Не более 2 МБ. JPG, JPEG, PNG или WEBP. Текущая фотография сохраняется, если новый файл не выбран.', 'identifiers_help' => 'СНИЛС и ИНН необязательны на этом этапе. При заполнении проверяется контрольная сумма.', 'registration_statuses' => ['draft' => 'Черновик', 'data_incomplete' => 'Не заполнены данные', 'documents_incomplete' => 'Не хватает документов', 'ready_for_review' => 'Готово к проверке', 'completed' => 'Завершено'],
    'documents' => ['other' => 'Другой документ', 'type' => 'Тип документа', 'files' => 'Файлы', 'series' => 'Серия', 'number' => 'Номер', 'issued_by' => 'Кем выдан', 'subdivision_code' => 'Код подразделения', 'issuing_country' => 'Страна выдачи', 'issue_date' => 'Дата выдачи', 'expiry_date' => 'Срок действия', 'representative' => 'Представитель', 'enrollment' => 'Зачисление'],
    'validation' => ['snils' => 'Укажите корректный СНИЛС из 11 цифр с верной контрольной суммой.', 'inn' => 'Укажите корректный ИНН из 10 или 12 цифр с верной контрольной суммой.', 'documents' => ['files_required' => 'Выберите хотя бы один файл.', 'file_mimetypes' => 'Разрешены только PDF, JPG, JPEG, PNG и WEBP.', 'file_max' => 'Размер каждого файла не должен превышать 2 МБ.', 'type_required' => 'Выберите тип документа.', 'expiry_after_issue' => 'Срок действия не может быть раньше даты выдачи.'], 'registration' => ['incomplete' => 'У ученика отсутствуют обязательные данные или документы.', 'not_ready' => 'Регистрация не готова к завершению.']],
    'responses' => ['saved' => 'Данные ученика сохранены.', 'submitted' => 'Личное дело отправлено на проверку.', 'completed' => 'Регистрация ученика завершена.'],
];
