@php
    $brandingAcademicYear = $academicYear ?? null;
    $brandingAcademicYearLabel = is_object($brandingAcademicYear)
        ? ($brandingAcademicYear->name ?? null)
        : $brandingAcademicYear;
@endphp

<style>
    .school-document-footer {
        position: fixed;
        right: 0;
        bottom: -13mm;
        left: 0;
        width: 100%;
        border-top: 1px solid #d1d5db;
        padding-top: 4px;
        color: #6b7280;
        font-size: 9px;
    }
    .school-document-footer-left { float: left; }
    .school-document-footer-center { text-align: center; }
    .school-document-footer-right { float: right; }
    .school-document-page:after { content: counter(page); }
    .school-document-pages:after { content: counter(pages); }
</style>

<footer class="school-document-footer">
    <span class="school-document-footer-left">Generated by School ERP</span>
    <span class="school-document-footer-right">Page <span class="school-document-page"></span> of <span class="school-document-pages"></span></span>
    <div class="school-document-footer-center">Учебный год: {{ $brandingAcademicYearLabel ?: '—' }}</div>
</footer>
