<?php

return [
    'title' => 'Complete student registration', 'documents_link' => 'Student documents', 'save' => 'Save data', 'not_provided' => 'Not provided', 'optional' => 'optional', 'yes' => 'Yes', 'no' => 'No', 'unknown' => 'Not specified',
    'sections' => ['readiness' => 'Personal file readiness', 'personal' => 'Personal details', 'representatives' => 'Parents and legal representatives', 'emergency' => 'Emergency contacts', 'enrollment' => 'Enrollment and education', 'needs' => 'Special educational conditions', 'documents' => 'Documents', 'finance' => 'Finance', 'completion' => 'Complete registration'],
    'readiness' => ['student' => 'Student data', 'documents' => 'Documents', 'enrollment' => 'Enrollment', 'overall' => 'Overall readiness', 'blocking' => 'Missing or blocking items', 'items' => ['name' => 'Last and first name', 'birth_date' => 'Date of birth', 'gender' => 'Gender', 'citizenship' => 'Citizenship', 'residential_address' => 'Residential address', 'phone' => 'Phone', 'contact' => 'Representative or emergency contact', 'academic_year' => 'Academic year', 'stage' => 'Stage', 'grade' => 'Grade', 'class' => 'Class', 'enrollment_date' => 'Enrollment date'], 'document_items' => ['photo' => 'Student photograph', 'birth_certificate' => 'Birth certificate', 'identity' => 'Passport or residence permit', 'previous_school' => 'Previous school document', 'medical' => 'Medical document']],
    'fields' => ['last_name' => 'Last name', 'first_name' => 'First name', 'patronymic' => 'Patronymic', 'gender' => 'Gender', 'male' => 'Male', 'female' => 'Female', 'birth_date' => 'Date of birth', 'birth_place' => 'Place of birth', 'citizenship' => 'Citizenship', 'citizenship_code' => 'Country code', 'phone' => 'Phone', 'email' => 'Email', 'residential_address' => 'Residential address', 'registration_address' => 'Registration address', 'photo' => 'Student photograph', 'snils' => 'SNILS', 'inn' => 'INN', 'relationship' => 'Relationship', 'full_name' => 'Full name', 'primary_contact' => 'Primary contact', 'legal_representative' => 'Legal representative', 'guardianship' => 'Guardianship authority', 'address' => 'Address', 'notes' => 'Notes', 'priority' => 'Priority', 'admission_context' => 'Admission context', 'previous_school' => 'Previous school', 'previous_country' => 'Previous-school country', 'previous_grade' => 'Previous grade', 'previous_class' => 'Previous class', 'previous_notes' => 'Previous education notes', 'has_ovz' => 'Special educational needs (OVZ)', 'has_disability' => 'Disability', 'requires_adapted_program' => 'Adapted program required', 'requires_special_conditions' => 'Special conditions required', 'special_conditions' => 'Special conditions', 'consent_status' => 'Consent status', 'consent_date' => 'Consent date'],
    'relationships' => ['father' => 'Father', 'mother' => 'Mother', 'guardian' => 'Guardian', 'custodian' => 'Custodian', 'other' => 'Other'], 'admission_contexts' => ['initial' => 'Initial admission', 'transfer' => 'Transfer', 'continuation' => 'Continuation', 're_enrollment' => 'Re-enrollment', 'other' => 'Other'],
    'add_representative' => 'Add representative', 'add_emergency' => 'Add contact', 'enrollment_missing' => 'No current enrollment was found.', 'finance_note' => 'Finance is read-only here and does not affect personal-file readiness.', 'documents_note' => 'Documents remain in the existing protected repository.', 'submit_review' => 'Submit for review', 'complete' => 'Complete registration', 'photo_help' => 'Up to 2 MB. JPG, JPEG, PNG or WEBP. The current photo is retained if no new file is selected.', 'identifiers_help' => 'SNILS and INN are optional in Phase 1. Supplied values are checksum-validated.', 'registration_statuses' => ['draft' => 'Draft', 'data_incomplete' => 'Data incomplete', 'documents_incomplete' => 'Documents incomplete', 'ready_for_review' => 'Ready for review', 'completed' => 'Completed'],
    'documents' => ['other' => 'Other document', 'type' => 'Document type', 'files' => 'Files', 'series' => 'Series', 'number' => 'Number', 'issued_by' => 'Issued by', 'subdivision_code' => 'Subdivision code', 'issuing_country' => 'Issuing country', 'issue_date' => 'Issue date', 'expiry_date' => 'Expiry date', 'representative' => 'Representative', 'enrollment' => 'Enrollment'],
    'validation' => ['snils' => 'Enter a valid 11-digit SNILS with a correct checksum.', 'inn' => 'Enter a valid 10- or 12-digit INN with a correct checksum.', 'documents' => ['files_required' => 'Select at least one file.', 'file_mimetypes' => 'Only PDF, JPG, JPEG, PNG and WEBP files are allowed.', 'file_max' => 'Each file must not exceed 2 MB.', 'type_required' => 'Select a document type.', 'expiry_after_issue' => 'The expiry date cannot be earlier than the issue date.'], 'registration' => ['incomplete' => 'The student is missing required data or documents.', 'not_ready' => 'Registration is not ready for completion.']],
    'responses' => ['saved' => 'Student data saved.', 'submitted' => 'The personal file was submitted for review.', 'completed' => 'Student registration completed.'],
];
