@extends('layouts.dashboard')
@section('content')
<div class="container-fluid py-3">
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="h3 mb-1">Завершение регистрации ученика</h1><div class="text-muted">{{ $student->full_name }} · {{ $student->statusLabel() }}</div></div><a class="btn btn-outline-primary" href="{{ route('dashboard.students.documents.index',$student) }}">Документы ученика</a></div>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card shadow-sm border-0 mb-4"><div class="card-body"><div class="d-flex justify-content-between"><strong>Готовность личного дела</strong><span>{{ $completion['overall_percentage'] }}%</span></div><div class="progress mt-2" style="height:12px"><div class="progress-bar" style="width:{{ $completion['overall_percentage'] }}%"></div></div><div class="mt-3">Готовность документов: {{ $completion['documents_completed_count'] }} из {{ $completion['documents_required_count'] }}</div>@if($completion['missing_items'])<div class="text-warning mt-2">Требуется дополнить: {{ implode(', ',$completion['missing_items']) }}</div>@endif</div></div>
<form method="post" action="{{ route('dashboard.students.complete-registration.update',$student) }}" enctype="multipart/form-data">@csrf @method('PUT')
<div class="card shadow-sm border-0 mb-4"><div class="card-header"><strong>1. Основные данные</strong></div><div class="card-body"><div class="row g-3">
<div class="col-md-4"><label class="form-label">Фамилия *</label><input class="form-control" name="last_name_ru" value="{{ old('last_name_ru',$student->last_name_ru) }}" required></div><div class="col-md-4"><label class="form-label">Имя *</label><input class="form-control" name="first_name_ru" value="{{ old('first_name_ru',$student->first_name_ru) }}" required></div><div class="col-md-4"><label class="form-label">Отчество</label><input class="form-control" name="patronymic_ru" value="{{ old('patronymic_ru',$student->patronymic_ru) }}"></div>
<div class="col-md-3"><label class="form-label">Пол *</label><select class="form-select" name="gender" required><option value="">Выберите</option><option value="male" @selected(old('gender',$student->gender)==='male')>Мужской</option><option value="female" @selected(old('gender',$student->gender)==='female')>Женский</option></select></div><div class="col-md-3"><label class="form-label">Дата рождения *</label><input type="date" class="form-control" name="birth_date" value="{{ old('birth_date',$student->birth_date?->format('Y-m-d')) }}" required></div><div class="col-md-3"><label class="form-label">Гражданство *</label><input class="form-control" name="nationality" value="{{ old('nationality',$student->nationality) }}" required></div><div class="col-md-3"><label class="form-label">Телефон *</label><input class="form-control" name="phone" value="{{ old('phone',$student->phone) }}" required></div><div class="col-md-6"><label class="form-label">Email</label><input type="email" class="form-control" name="email" value="{{ old('email',$student->email) }}"></div><div class="col-md-6"><label class="form-label">Адрес *</label><input class="form-control" name="address" value="{{ old('address',$student->address) }}" required></div>
<div class="col-12"><label class="form-label">Фотография ученика</label><div class="d-flex align-items-center gap-3 mb-2">@if($student->photo)<img src="{{ Storage::disk(config('filesystems.uploads.public'))->url($student->photo) }}" style="width:100px;height:100px;object-fit:contain" alt="Фотография ученика">@else<div class="bg-light border rounded d-flex align-items-center justify-content-center" style="width:100px;height:100px">Нет фото</div>@endif</div><input type="file" class="form-control" name="photo" accept="image/jpeg,image/png,image/webp"><div class="form-text">Не более 2 МБ. Форматы: JPG, JPEG, PNG, WEBP. Если файл не выбран, текущая фотография сохранится.</div></div>
</div></div></div>
@php($profile=$student->documents??[])
<div class="card shadow-sm border-0 mb-4"><div class="card-header"><strong>2. Родители и контакты</strong></div><div class="card-body"><div class="row g-3">@foreach(['father'=>'Отец','mother'=>'Мать'] as $key=>$label)<div class="col-12"><h2 class="h6">{{ $label }}</h2></div><div class="col-md-3"><input class="form-control" name="{{ $key }}_name" value="{{ old($key.'_name',data_get($profile,$key.'.name')) }}" placeholder="ФИО"></div><div class="col-md-3"><input class="form-control" name="{{ $key }}_phone" value="{{ old($key.'_phone',data_get($profile,$key.'.phone')) }}" placeholder="Телефон"></div><div class="col-md-3"><input type="email" class="form-control" name="{{ $key }}_email" value="{{ old($key.'_email',data_get($profile,$key.'.email')) }}" placeholder="Email"></div><div class="col-md-3"><input class="form-control" name="{{ $key }}_identity" value="{{ old($key.'_identity',data_get($profile,$key.'.identity')) }}" placeholder="Паспорт / удостоверение"></div>@endforeach
<div class="col-12"><h2 class="h6">Экстренный контакт</h2></div><div class="col-md-4"><input class="form-control" name="emergency_name" value="{{ old('emergency_name',data_get($profile,'emergency.name')) }}" placeholder="ФИО"></div><div class="col-md-4"><input class="form-control" name="emergency_relationship" value="{{ old('emergency_relationship',data_get($profile,'emergency.relationship')) }}" placeholder="Кем приходится"></div><div class="col-md-4"><input class="form-control" name="emergency_phone" value="{{ old('emergency_phone',data_get($profile,'emergency.phone')) }}" placeholder="Телефон"></div><div class="col-12"><label class="form-label">Медицинские примечания</label><textarea class="form-control" name="medical_notes">{{ old('medical_notes',data_get($profile,'medical_notes')) }}</textarea></div>
</div><div class="form-text mt-3">До отправки на проверку должен быть указан хотя бы один телефон родителя или экстренного контакта.</div></div></div>
<div class="card shadow-sm border-0 mb-4"><div class="card-header"><strong>3. Обучение</strong></div><div class="card-body">@if($student->currentEnrollment){{ $student->currentEnrollment->academicYear?->name }} · {{ $student->currentEnrollment->stage?->name }} · {{ $student->currentEnrollment->grade?->name }} · {{ $student->currentEnrollment->schoolClass?->name }}@else<span class="text-warning">Активное зачисление не найдено.</span>@endif</div></div>
<div class="card shadow-sm border-0 mb-4"><div class="card-header"><strong>4. Финансы (только просмотр)</strong></div><div class="card-body"><div class="table-responsive"><table class="table"><thead><tr><th>Счёт</th><th>Итого</th><th>Оплачено</th><th>Остаток</th></tr></thead><tbody>@forelse($student->invoices as $invoice)<tr><td><a href="{{ route('dashboard.invoices.show',$invoice) }}">{{ $invoice->display_number }}</a></td><td>{{ $invoice->total_amount }} EGP</td><td>{{ $invoice->paid_amount }} EGP</td><td>{{ $invoice->remaining_amount }} EGP</td></tr>@empty<tr><td colspan="4">Счета отсутствуют.</td></tr>@endforelse</tbody></table></div></div></div>
<div class="d-flex flex-wrap gap-2"><button class="btn btn-primary">Сохранить данные</button><a class="btn btn-outline-primary" href="{{ route('dashboard.students.documents.index',$student) }}">5. Документы</a></div></form>
<div class="card shadow-sm border-0 mt-4"><div class="card-header"><strong>6. Проверка</strong></div><div class="card-body"><form method="post" action="{{ route('dashboard.students.registration-review.submit',$student) }}">@csrf <button class="btn btn-warning" @disabled(!$completion['can_submit_for_review'] || $student->status===\App\Models\Student::STATUS_UNDER_REVIEW)>Отправить на проверку</button></form>@can('manage users')<form class="mt-2" method="post" action="{{ route('dashboard.students.registration-review.complete',$student) }}" onsubmit="return confirm('Подтвердить завершение регистрации?')">@csrf <button class="btn btn-success" @disabled($student->status!==\App\Models\Student::STATUS_UNDER_REVIEW)>Завершить регистрацию</button></form>@endcan</div></div>
</div>
@endsection
