@extends('layouts.dashboard')
@section('content')
@php
    $t='student_registration.';
    $legacy=$student->documents??[];
    $representatives=$student->representatives->map(fn($r)=>$r->toArray())->values();
    foreach(['father','mother'] as $preset) if(!$representatives->contains('relationship_type',$preset)) $representatives->push(array_merge(['relationship_type'=>$preset,'full_name'=>''],(array)data_get($legacy,$preset,[])));
    $contacts=$student->emergencyContacts->map(fn($c)=>$c->toArray())->values();
    if($contacts->isEmpty()) $contacts->push(array_merge(['full_name'=>'','relationship'=>'','phone'=>'','priority'=>1],(array)data_get($legacy,'emergency',[])));
    $need=$student->educationalNeed;
    $tri=[null=>__($t.'unknown'),0=>__($t.'no'),1=>__($t.'yes')];
@endphp
<div class="container-fluid py-3" @if(app()->getLocale()==='ar') dir="rtl" @endif>
 <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="h3 mb-1">{{ __($t.'title') }}</h1><div class="text-muted">{{ $student->full_name }} · {{ __($t.'registration_statuses.'.($student->registration_status?:'draft')) }}</div></div><a class="btn btn-outline-primary" href="{{ route('dashboard.students.documents.index',$student) }}">{{ __($t.'documents_link') }}</a></div>
 @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

 <div class="card shadow-sm border-0 mb-4"><div class="card-header"><strong>{{ __($t.'sections.readiness') }}</strong></div><div class="card-body"><div class="row g-3">
 @foreach(['student_data_percentage'=>'student','documents_percentage'=>'documents','enrollment_percentage'=>'enrollment','overall_percentage'=>'overall'] as $key=>$label)<div class="col-md-3"><div class="d-flex justify-content-between"><span>{{ __($t.'readiness.'.$label) }}</span><strong>{{ $completion[$key] }}%</strong></div><div class="progress mt-2" style="height:10px"><div class="progress-bar" style="width:{{ $completion[$key] }}%"></div></div></div>@endforeach
 </div>@php($blocking=array_merge($completion['missing_student_items'],$completion['missing_document_items'],$completion['missing_enrollment_items']))@if($blocking)<div class="alert alert-warning mt-3 mb-0"><strong>{{ __($t.'readiness.blocking') }}:</strong> {{ implode(', ',$blocking) }}</div>@endif</div></div>

 <form method="post" action="{{ route('dashboard.students.complete-registration.update',$student) }}" enctype="multipart/form-data">@csrf @method('PUT')
 <div class="card shadow-sm border-0 mb-4"><div class="card-header"><strong>2. {{ __($t.'sections.personal') }}</strong></div><div class="card-body"><div class="row g-3">
 @foreach([['last_name_ru','last_name'],['first_name_ru','first_name'],['patronymic_ru','patronymic']] as [$name,$label])<div class="col-md-4"><label class="form-label">{{ __($t.'fields.'.$label) }} @if($name!=='patronymic_ru')*@endif</label><input class="form-control" name="{{ $name }}" value="{{ old($name,$student->$name) }}" @required($name!=='patronymic_ru')></div>@endforeach
 <div class="col-md-3"><label class="form-label">{{ __($t.'fields.gender') }} *</label><select class="form-select" name="gender" required><option value="">{{ __($t.'unknown') }}</option><option value="male" @selected(old('gender',$student->gender)==='male')>{{ __($t.'fields.male') }}</option><option value="female" @selected(old('gender',$student->gender)==='female')>{{ __($t.'fields.female') }}</option></select></div>
 <div class="col-md-3"><label class="form-label">{{ __($t.'fields.birth_date') }} *</label><input type="date" class="form-control" name="birth_date" value="{{ old('birth_date',$student->birth_date?->format('Y-m-d')) }}" required></div>
 <div class="col-md-3"><label class="form-label">{{ __($t.'fields.birth_place') }}</label><input class="form-control" name="birth_place" value="{{ old('birth_place',$student->birth_place) }}"></div>
 <div class="col-md-3"><label class="form-label">{{ __($t.'fields.citizenship') }} *</label><input class="form-control" name="nationality" value="{{ old('nationality',$student->nationality) }}" required></div>
 <div class="col-md-2"><label class="form-label">{{ __($t.'fields.citizenship_code') }}</label><input class="form-control text-uppercase" maxlength="2" name="citizenship_code" value="{{ old('citizenship_code',$student->citizenship_code) }}"></div>
 <div class="col-md-4"><label class="form-label">{{ __($t.'fields.phone') }} *</label><input class="form-control" name="phone" value="{{ old('phone',$student->phone) }}" required></div><div class="col-md-6"><label class="form-label">{{ __($t.'fields.email') }}</label><input type="email" class="form-control" name="email" value="{{ old('email',$student->email) }}"></div>
 <div class="col-md-6"><label class="form-label">{{ __($t.'fields.residential_address') }} *</label><textarea class="form-control" name="residential_address" required>{{ old('residential_address',$student->residential_address?:$student->address) }}</textarea></div><div class="col-md-6"><label class="form-label">{{ __($t.'fields.registration_address') }}</label><textarea class="form-control" name="registration_address">{{ old('registration_address',$student->registration_address) }}</textarea></div>
 <div class="col-md-6"><label class="form-label">{{ __($t.'fields.snils') }} ({{ __($t.'optional') }})</label><input class="form-control" name="snils" value="{{ old('snils',$student->snils) }}"></div><div class="col-md-6"><label class="form-label">{{ __($t.'fields.inn') }} ({{ __($t.'optional') }})</label><input class="form-control" name="inn" value="{{ old('inn',$student->inn) }}"></div><div class="col-12 form-text">{{ __($t.'identifiers_help') }}</div>
 <div class="col-12"><label class="form-label">{{ __($t.'fields.photo') }}</label><div class="mb-2">@if($student->photo)<img src="{{ Storage::disk(config('filesystems.uploads.public'))->url($student->photo) }}" class="rounded border" style="width:100px;height:100px;object-fit:contain" alt="">@endif</div><input type="file" class="form-control" name="photo" accept="image/jpeg,image/png,image/webp"><div class="form-text">{{ __($t.'photo_help') }}</div></div>
 </div></div></div>

 <div class="card shadow-sm border-0 mb-4"><div class="card-header d-flex justify-content-between"><strong>3. {{ __($t.'sections.representatives') }}</strong><button class="btn btn-sm btn-outline-primary" type="button" data-add="representative">{{ __($t.'add_representative') }}</button></div><div class="card-body" id="representatives">@foreach(old('representatives',$representatives->all()) as $i=>$r)@include('dashboard.students.partials.representative-form',['i'=>$i,'r'=>$r])@endforeach</div></div>
 <div class="card shadow-sm border-0 mb-4"><div class="card-header d-flex justify-content-between"><strong>4. {{ __($t.'sections.emergency') }}</strong><button class="btn btn-sm btn-outline-primary" type="button" data-add="emergency">{{ __($t.'add_emergency') }}</button></div><div class="card-body" id="emergency-contacts">@foreach(old('emergency_contacts',$contacts->all()) as $i=>$c)@include('dashboard.students.partials.emergency-contact-form',['i'=>$i,'c'=>$c])@endforeach</div></div>

 <div class="card shadow-sm border-0 mb-4"><div class="card-header"><strong>5. {{ __($t.'sections.enrollment') }}</strong></div><div class="card-body">@if($student->currentEnrollment)<p>{{ $student->currentEnrollment->academicYear?->name }} · {{ $student->currentEnrollment->stage?->name }} · {{ $student->currentEnrollment->grade?->name }} · {{ $student->currentEnrollment->schoolClass?->name }}</p><div class="row g-3"><div class="col-md-4"><label class="form-label">{{ __($t.'fields.admission_context') }}</label><select class="form-select" name="admission_context"><option value="">{{ __($t.'unknown') }}</option>@foreach(__('student_registration.admission_contexts') as $value=>$label)<option value="{{ $value }}" @selected(old('admission_context',$student->currentEnrollment->admission_context)===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">{{ __($t.'fields.previous_school') }}</label><input class="form-control" name="previous_school_name" value="{{ old('previous_school_name',$student->currentEnrollment->previous_school_name) }}"></div><div class="col-md-4"><label class="form-label">{{ __($t.'fields.previous_country') }}</label><input maxlength="2" class="form-control text-uppercase" name="previous_school_country_code" value="{{ old('previous_school_country_code',$student->currentEnrollment->previous_school_country_code) }}"></div><div class="col-md-4"><label class="form-label">{{ __($t.'fields.previous_grade') }}</label><input class="form-control" name="previous_grade" value="{{ old('previous_grade',$student->currentEnrollment->previous_grade) }}"></div><div class="col-md-4"><label class="form-label">{{ __($t.'fields.previous_class') }}</label><input class="form-control" name="previous_class" value="{{ old('previous_class',$student->currentEnrollment->previous_class) }}"></div><div class="col-md-12"><label class="form-label">{{ __($t.'fields.previous_notes') }}</label><textarea class="form-control" name="previous_education_notes">{{ old('previous_education_notes',$student->currentEnrollment->previous_education_notes) }}</textarea></div></div>@else<span class="text-warning">{{ __($t.'enrollment_missing') }}</span>@endif</div></div>

 <div class="card shadow-sm border-0 mb-4"><div class="card-header"><strong>6. {{ __($t.'sections.needs') }}</strong></div><div class="card-body"><div class="row g-3">@foreach(['has_ovz','has_disability','requires_adapted_program','requires_special_conditions'] as $field)<div class="col-md-3"><label class="form-label">{{ __($t.'fields.'.$field) }}</label><select class="form-select" name="{{ $field }}">@foreach($tri as $value=>$label)<option value="{{ $value }}" @selected((string)old($field,$need?->$field)===(string)$value)>{{ $label }}</option>@endforeach</select></div>@endforeach<div class="col-md-6"><label class="form-label">{{ __($t.'fields.special_conditions') }}</label><textarea class="form-control" name="special_conditions">{{ old('special_conditions',$need?->special_conditions) }}</textarea></div><div class="col-md-6"><label class="form-label">{{ __($t.'fields.notes') }}</label><textarea class="form-control" name="educational_needs_notes">{{ old('educational_needs_notes',$need?->notes) }}</textarea></div><div class="col-md-6"><label class="form-label">{{ __($t.'fields.consent_status') }}</label><input class="form-control" name="consent_status" value="{{ old('consent_status',$need?->consent_status) }}"></div><div class="col-md-6"><label class="form-label">{{ __($t.'fields.consent_date') }}</label><input type="date" class="form-control" name="consent_received_at" value="{{ old('consent_received_at',$need?->consent_received_at?->format('Y-m-d')) }}"></div></div></div></div>

 <div class="card shadow-sm border-0 mb-4"><div class="card-header"><strong>7. {{ __($t.'sections.documents') }}</strong></div><div class="card-body"><p>{{ __($t.'documents_note') }}</p><a class="btn btn-outline-primary" href="{{ route('dashboard.students.documents.index',$student) }}">{{ __($t.'documents_link') }}</a></div></div>
 <div class="card shadow-sm border-0 mb-4"><div class="card-header"><strong>8. {{ __($t.'sections.finance') }}</strong></div><div class="card-body"><p>{{ __($t.'finance_note') }}</p><div class="table-responsive"><table class="table"><tbody>@forelse($student->invoices as $invoice)<tr><td><a href="{{ route('dashboard.invoices.show',$invoice) }}">{{ $invoice->display_number }}</a></td><td>{{ $invoice->total_amount }} EGP</td><td>{{ $invoice->remaining_amount }} EGP</td></tr>@empty<tr><td>{{ __($t.'not_provided') }}</td></tr>@endforelse</tbody></table></div></div></div>
 <button class="btn btn-primary mb-4">{{ __($t.'save') }}</button></form>

 <div class="card shadow-sm border-0"><div class="card-header"><strong>9. {{ __($t.'sections.completion') }}</strong></div><div class="card-body"><p>{{ __($t.'readiness.overall') }}: <strong>{{ $completion['overall_percentage'] }}%</strong></p><form method="post" action="{{ route('dashboard.students.registration-review.submit',$student) }}">@csrf <button class="btn btn-warning" @disabled(!$completion['can_submit_for_review'] || $student->status===\App\Models\Student::STATUS_UNDER_REVIEW)>{{ __($t.'submit_review') }}</button></form>@can('manage users')<form class="mt-2" method="post" action="{{ route('dashboard.students.registration-review.complete',$student) }}">@csrf <button class="btn btn-success" @disabled($student->status!==\App\Models\Student::STATUS_UNDER_REVIEW)>{{ __($t.'complete') }}</button></form>@endcan</div></div>
</div>
<template id="representative-template">@include('dashboard.students.partials.representative-form',['i'=>'__INDEX__','r'=>[]])</template><template id="emergency-template">@include('dashboard.students.partials.emergency-contact-form',['i'=>'__INDEX__','c'=>[]])</template>
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-add]').forEach(button=>button.addEventListener('click',()=>{const type=button.dataset.add,target=document.getElementById(type==='representative'?'representatives':'emergency-contacts'),template=document.getElementById(type+'-template');target.insertAdjacentHTML('beforeend',template.innerHTML.replaceAll('__INDEX__',target.querySelectorAll('[data-entry]').length));}));});</script>@endpush
@endsection
