@extends('layouts.dashboard')
@section('content')
<div class="container-fluid py-3"><div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3">Документы ученика</h1><div>{{ $student->full_name }} · {{ $student->statusLabel() }}</div></div><a class="btn btn-outline-secondary" href="{{ route('dashboard.students.complete-registration.edit',$student) }}">К завершению регистрации</a></div>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><strong>Готовность документов: {{ $completion['documents_completed_count'] }} из {{ $completion['documents_required_count'] }}</strong><div class="progress my-2"><div class="progress-bar" style="width:{{ $completion['documents_percentage'] }}%"></div></div>@if($completion['missing_items'])<div class="text-warning">Требуется дополнить: {{ implode(', ',$completion['missing_items']) }}</div>@endif</div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-header"><strong>Добавить документ</strong></div><div class="card-body"><form method="post" enctype="multipart/form-data" action="{{ route('dashboard.students.documents.store',$student) }}">@csrf <div class="row g-3"><div class="col-md-3"><label class="form-label">Тип документа</label><select class="form-select" name="type" required>@foreach(\App\Models\StudentFile::TYPES as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Файлы</label><input class="form-control" type="file" name="files[]" multiple required accept="application/pdf,image/jpeg,image/png,image/webp"></div><div class="col-md-5"><label class="form-label">Описание</label><input class="form-control" name="description"></div><div class="col-md-3"><label class="form-label">Дата выдачи</label><input class="form-control" type="date" name="issue_date"></div><div class="col-md-3"><label class="form-label">Срок действия</label><input class="form-control" type="date" name="expiry_date"></div><div class="col-12"><div class="form-text">Допустимый размер каждого файла: не более 2 МБ. Форматы: PDF, JPG, JPEG, PNG, WEBP.</div><button class="btn btn-primary mt-2">Добавить документ</button></div></div></form></div></div>
@include('dashboard.students.partials.document-list',['files'=>$activeFiles,'archived'=>false])
<details class="mt-4"><summary class="h5">Архивированные документы ({{ $archivedFiles->count() }})</summary><div class="mt-3">@include('dashboard.students.partials.document-list',['files'=>$archivedFiles,'archived'=>true])</div></details>
</div>
@endsection
