@extends('layouts.dashboard')
@section('content')
@php
 $student=$profile['student']; $enrollment=$profile['current_enrollment']; $completion=$profile['completion'];
 $financial=$profile['financial']; $contacts=$profile['contacts']; $subscriptions=$profile['subscriptions'];
 $invoices=$profile['invoices']; $payments=$profile['payments']; $documents=$profile['documents']; $timeline=$profile['timeline'];
 $empty='Данные не указаны.';
 $categories=['tuition'=>'Обучение','tuition_regular'=>'Обучение','tuition_family'=>'Обучение','tuition_external'=>'Экстернат','registration'=>'Регистрационный взнос','transport'=>'Транспорт','food'=>'Питание','uniform'=>'Школьная форма','activity'=>'Дополнительные занятия','extra_classes'=>'Дополнительные занятия','other'=>'Дополнительные услуги'];
$statuses=['active'=>'Активна','suspended'=>'Приостановлена','cancelled'=>'Завершена','completed'=>'Завершена'];
@endphp
<div class="container-fluid py-3">
@can('manage students')<div class="d-flex flex-wrap gap-2 mb-3"><a class="btn btn-outline-primary" href="{{ route('dashboard.students.subscriptions.index',$student) }}">Управление услугами</a><a class="btn btn-outline-primary" href="{{ route('dashboard.students.subscriptions.create',$student) }}">Добавить услугу</a><a class="btn btn-outline-secondary" href="{{ route('dashboard.students.subscriptions.renew',$student) }}">Продлить услуги</a></div>@endcan
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="d-flex flex-column flex-lg-row align-items-lg-center gap-4">
 <div class="text-center">@if($profile['photo_url'])<img src="{{ $profile['photo_url'] }}" alt="Фотография ученика" class="rounded-circle" style="width:140px;height:140px;object-fit:cover">@else<div class="rounded-circle bg-light border d-flex align-items-center justify-content-center mx-auto fs-1 text-primary" style="width:140px;height:140px">{{ mb_substr($student->full_name ?: 'У',0,1) }}</div>@endif</div>
 <div class="flex-grow-1"><div class="small text-muted">Профиль ученика</div><h1 class="h3 mb-2">{{ $student->full_name ?: $empty }}</h1><div class="d-flex flex-wrap gap-2 mb-3"><span class="badge bg-primary">ID #{{ $student->id }}</span><span class="badge bg-secondary">{{ $student->statusLabel() }}</span></div><div class="row g-2 small"><div class="col-md-4"><strong>Учебный год:</strong> {{ $enrollment?->academicYear?->name ?: $empty }}</div><div class="col-md-4"><strong>Ступень:</strong> {{ $enrollment?->stage?->name ?: $empty }}</div><div class="col-md-4"><strong>Класс:</strong> {{ collect([$enrollment?->grade?->name,$enrollment?->schoolClass?->name])->filter()->implode(' · ') ?: $empty }}</div><div class="col-md-4"><strong>Форма обучения:</strong> {{ $enrollment?->enrollmentMode?->name_ru ?: $empty }}</div><div class="col-md-4"><strong>Готовность профиля:</strong> {{ $completion['overall_percentage'] }}%</div><div class="col-md-4"><strong>Готовность документов:</strong> {{ $completion['documents_percentage'] }}%</div></div></div>
 <div class="d-flex flex-wrap gap-2 align-self-lg-start">@can('manage students')<a class="btn btn-primary" href="{{ route('dashboard.students.complete-registration.edit',$student) }}">Завершить регистрацию</a><a class="btn btn-outline-primary" href="{{ route('dashboard.students.documents.index',$student) }}">Документы</a>@endcan @can('update students')<a class="btn btn-outline-secondary" href="{{ route('dashboard.students.edit',$student) }}">Редактировать данные</a>@endcan @can('view invoices')<a class="btn btn-outline-success" href="{{ route('dashboard.students.finance',$student) }}">Финансы</a>@endcan @can('manage invoices')<a class="btn btn-outline-primary" href="{{ route('dashboard.students.invoices.create',$student) }}">Создать счёт</a>@php
    $payableInvoices = $invoices->whereIn('status', ['unpaid', 'partial']);
@endphp<a class="btn btn-success" href="{{ $payableInvoices->count() === 1 ? route('dashboard.invoices.payments.create',$payableInvoices->first()) : route('dashboard.students.finance',$student) }}">Принять оплату</a>@endcan <a class="btn btn-outline-dark" href="{{ route('dashboard.students.print',$student) }}" target="_blank">Печать профиля</a></div>
</div></div></div>

<ul class="nav nav-tabs flex-nowrap overflow-auto mb-3" role="tablist">@foreach(['overview'=>'Обзор','contacts'=>'Родители и контакты','academic'=>'Обучение','services'=>'Услуги','finance'=>'Финансы','documents'=>'Документы','timeline'=>'История'] as $key=>$label)<li class="nav-item"><button class="nav-link text-nowrap {{ $loop->first?'active':'' }}" data-bs-toggle="tab" data-bs-target="#student-{{ $key }}" type="button">{{ $label }}</button></li>@endforeach</ul>
<div class="tab-content">
<div class="tab-pane fade show active" id="student-overview"><div class="row g-3">@foreach([['Статус регистрации',$student->statusLabel()],['Готовность профиля',$completion['overall_percentage'].'%'],['Готовность документов',$completion['documents_percentage'].'%'],['Учебный год',$enrollment?->academicYear?->name],['Класс',collect([$enrollment?->grade?->name,$enrollment?->schoolClass?->name])->filter()->implode(' · ')],['Форма обучения',$enrollment?->enrollmentMode?->name_ru],['Активные услуги',$subscriptions->where('status','active')->count()],['Финансовый баланс',$financial['remaining'].' EGP']] as [$label,$value])<div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-muted">{{ $label }}</div><div class="fw-semibold mt-1">{{ filled($value)?$value:$empty }}</div></div></div></div>@endforeach
<div class="col-12"><div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h6">Что требуется дополнить</h2>@if($completion['missing_items'])<ul class="mb-0">@foreach($completion['missing_items'] as $item)<li>{{ $item }}</li>@endforeach</ul>@else<div class="text-success">Обязательные данные и документы собраны.</div>@endif</div></div></div></div></div>

<div class="tab-pane fade" id="student-contacts"><div class="row g-3">@foreach(['father'=>'Отец','mother'=>'Мать'] as $key=>$label)@php
    $person = data_get($contacts, $key, []);
@endphp<div class="col-lg-6"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">{{ $label }}</h2><dl class="row mb-0">@foreach(['name'=>'ФИО','phone'=>'Телефон','email'=>'Email','identity'=>'Паспорт / удостоверение'] as $field=>$title)<dt class="col-sm-5">{{ $title }}</dt><dd class="col-sm-7">{{ data_get($person, $field) ?: ($field === 'identity' ? data_get($person, 'passport') : null) ?: $empty }}</dd>@endforeach</dl></div></div></div>@endforeach
@php
    $emergency = data_get($contacts, 'emergency', []);
@endphp<div class="col-lg-6"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Экстренный контакт</h2><p>{{ data_get($emergency,'name') ?: data_get($contacts,'emergency_contact') ?: $empty }}</p><p>{{ data_get($emergency,'relationship') ?: $empty }} · {{ data_get($emergency,'phone') ?: $empty }}</p></div></div></div><div class="col-lg-6"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Ученик</h2><p>Имя на английском языке: {{ data_get($contacts,'name_en') ?: $empty }}</p><p>Имя на арабском языке: {{ data_get($contacts,'name_ar') ?: $empty }}</p><p>Телефон: {{ $student->phone ?: $empty }}</p><p>Адрес: {{ $student->address ?: $empty }}</p><p>Гражданство: {{ $student->nationality ?: $empty }}</p><p>Дата рождения: {{ $student->birth_date?->format('d.m.Y') ?: $empty }}</p></div></div></div></div></div>

<div class="tab-pane fade" id="student-academic"><div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">Текущие учебные данные</h2><div class="row g-3">@foreach([['Учебный год',$enrollment?->academicYear?->name],['Ступень',$enrollment?->stage?->name],['Класс',$enrollment?->grade?->name],['Учебная группа',$enrollment?->schoolClass?->name],['Форма обучения',$enrollment?->enrollmentMode?->name_ru],['Статус зачисления',$enrollment?->status_label],['Дата зачисления',$enrollment?->date?->format('d.m.Y')]] as [$label,$value])<div class="col-md-4"><div class="small text-muted">{{ $label }}</div><div>{{ $value ?: $empty }}</div></div>@endforeach</div><div class="d-flex flex-wrap gap-2 mt-4">@if(Route::has('dashboard.attendance.reports.student'))<a class="btn btn-sm btn-outline-primary" href="{{ route('dashboard.attendance.reports.student',['student_id'=>$student->id]) }}">Посещаемость</a>@endif @if(Route::has('dashboard.student-grades.index'))<a class="btn btn-sm btn-outline-primary" href="{{ route('dashboard.student-grades.index',['student_id'=>$student->id]) }}">Оценки</a>@endif @if(Route::has('dashboard.exams.index'))<a class="btn btn-sm btn-outline-primary" href="{{ route('dashboard.exams.index') }}">Экзамены</a>@endif</div></div></div></div>

<div class="tab-pane fade" id="student-services"><div class="row g-3">@forelse($subscriptions as $subscription)@php
    $snapshot = $subscription->profile_snapshot;
    $metadata = $subscription->metadata ?? $snapshot?->metadata ?? [];
@endphp<div class="col-md-6 col-xl-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="d-flex justify-content-between gap-2"><h2 class="h6">{{ $subscription->fee?->name_ru ?: 'Услуга' }}</h2><span class="badge {{ $subscription->status==='active'?'bg-success':'bg-secondary' }}">{{ $statuses[$subscription->status]??$subscription->status }}</span></div><div class="small text-muted mb-3">{{ $categories[$subscription->fee?->category]??'Дополнительная услуга' }}</div><dl class="row small mb-0"><dt class="col-5">Учебный год</dt><dd class="col-7">{{ $subscription->profileEnrollment?->academicYear?->name ?: $empty }}</dd><dt class="col-5">Начало</dt><dd class="col-7">{{ $subscription->start_date?->format('d.m.Y') ?: $empty }}</dd><dt class="col-5">Окончание</dt><dd class="col-7">{{ $subscription->end_date?->format('d.m.Y') ?: $empty }}</dd><dt class="col-5">Цена</dt><dd class="col-7">{{ $subscription->negotiated_price ?: $snapshot?->amount ?: '—' }}{{ $subscription->negotiated_price||$snapshot ? ' EGP':'' }}</dd><dt class="col-5">Период</dt><dd class="col-7">{{ ['monthly'=>'Ежемесячно','yearly'=>'Ежегодно','daily'=>'Ежедневно','once'=>'Однократно','package'=>'Пакет'][$metadata['payment_period']??'']??($metadata['payment_period']??$empty) }}</dd></dl>@if($metadata)<div class="border-top mt-2 pt-2 small">@foreach(collect($metadata)->only(['area','route','stop','meal_plan','item','size','option_value']) as $key=>$value)<span class="badge bg-light text-dark me-1">{{ $value }}</span>@endforeach</div>@endif</div></div></div>@empty<div class="col-12"><div class="alert alert-light">Услуги не подключены.</div></div>@endforelse</div></div>

<div class="tab-pane fade" id="student-finance">@can('view invoices')<div class="d-flex flex-wrap gap-2 mb-3"><span class="badge {{ bccomp($financial['remaining'],'0.00',2)===1?'bg-warning text-dark':'bg-success' }}">{{ bccomp($financial['remaining'],'0.00',2)===1?'Есть задолженность':'Задолженности нет' }}</span><span class="badge bg-light text-dark">Предстоящие платежи: {{ $financial['upcoming_count'] }}</span></div><div class="row g-3 mb-4">@foreach([['Начислено',$financial['invoiced']],['Оплачено',$financial['paid']],['Остаток',$financial['remaining']],['Просрочено',$financial['overdue']]] as [$label,$amount])<div class="col-6 col-xl-3"><div class="card border-0 shadow-sm"><div class="card-body"><div class="small text-muted">{{ $label }}</div><strong>{{ number_format((float)$amount,2,'.',' ') }} EGP</strong></div></div></div>@endforeach</div><div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Счета ({{ $financial['invoice_count'] }})</h2><div class="table-responsive"><table class="table"><thead><tr><th>Номер</th><th>Учебный год</th><th>Дата</th><th>Итого</th><th>Оплачено</th><th>Остаток</th><th>Статус</th></tr></thead><tbody>@forelse($invoices as $invoice)<tr><td><a href="{{ route('dashboard.invoices.show',$invoice) }}">{{ $invoice->display_number }}</a></td><td>{{ $invoice->academicYear?->name ?: '—' }}</td><td>{{ $invoice->created_at?->format('d.m.Y') }}</td><td>{{ $invoice->total_amount }} EGP</td><td>{{ $invoice->paid_amount }} EGP</td><td>{{ $invoice->remaining_amount }} EGP</td><td>{{ ['unpaid'=>'Не оплачен','partial'=>'Частично оплачен','paid'=>'Оплачен'][$invoice->status]??$invoice->status }}</td></tr>@empty<tr><td colspan="7">Счета отсутствуют.</td></tr>@endforelse</tbody></table></div></div></div><div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">Платежи ({{ $financial['payment_count'] }})</h2><div class="table-responsive"><table class="table"><thead><tr><th>Номер</th><th>Дата</th><th>Способ</th><th>Сумма</th><th>Счёт</th><th>Касса</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ $payment->payment_number ?: '—' }}</td><td>{{ ($payment->paid_at??$payment->created_at)?->format('d.m.Y H:i') }}</td><td>{{ ['cash'=>'Наличные','card'=>'Банковская карта','bank'=>'Банковский перевод','transfer'=>'Банковский перевод'][$payment->payment_method]??'Не указан' }}</td><td>{{ $payment->amount }} EGP</td><td><a href="{{ route('dashboard.invoices.show',$payment->invoice_id) }}">{{ $payment->invoice?->display_number }}</a></td><td>{{ $payment->cashAccount?->name ?: '—' }}</td></tr>@empty<tr><td colspan="6">Платежи отсутствуют.</td></tr>@endforelse</tbody></table></div></div></div>@else<div class="alert alert-secondary">Финансовые данные недоступны.</div>@endcan</div>

<div class="tab-pane fade" id="student-documents">@can('manage students')<div class="card border-0 shadow-sm"><div class="card-body"><div class="row g-3 mb-3"><div class="col-md-3">Фото: <strong>{{ $student->photo?'загружено':'отсутствует' }}</strong></div><div class="col-md-3">Активных документов: <strong>{{ $documents['active_count'] }}</strong></div><div class="col-md-3">В архиве: <strong>{{ $documents['archived_count'] }}</strong></div><div class="col-md-3">Готовность: <strong>{{ $completion['documents_percentage'] }}%</strong></div></div>@if($completion['missing_items'])<div class="alert alert-warning">Не хватает: {{ implode(', ',$completion['missing_items']) }}</div>@endif @foreach($documents['expiry_warnings'] as $file)<div class="alert alert-danger py-2">{{ $file->typeLabel() }}: {{ $file->expiryStatus() }} ({{ $file->expiry_date?->format('d.m.Y') }})</div>@endforeach<h2 class="h6">Последние документы</h2><ul>@forelse($documents['latest'] as $file)<li>{{ $file->typeLabel() }} · {{ $file->created_at?->format('d.m.Y') }}</li>@empty<li>{{ $empty }}</li>@endforelse</ul><a class="btn btn-primary" href="{{ route('dashboard.students.documents.index',$student) }}">Открыть документы</a><a class="btn btn-outline-primary" href="{{ route('dashboard.students.documents.index',$student) }}">Добавить документ</a></div></div>@else<div class="alert alert-secondary">Документы доступны только сотрудникам с разрешением на управление учениками.</div>@endcan</div>

<div class="tab-pane fade" id="student-timeline"><div class="card border-0 shadow-sm"><div class="card-body"><div class="list-group list-group-flush">@forelse($timeline as $event)<div class="list-group-item px-0" data-timeline-at="{{ $event['at']->toISOString() }}"><div class="d-flex justify-content-between gap-2"><strong>@if($event['url'])<a href="{{ $event['url'] }}">{{ $event['label'] }}</a>@else{{ $event['label'] }}@endif</strong><span class="small text-muted">{{ $event['at']->format('d.m.Y H:i') }}</span></div>@if($event['description'])<div>{{ $event['description'] }}</div>@endif @if($event['actor'])<div class="small text-muted">Сотрудник: {{ $event['actor'] }}</div>@endif</div>@empty<div class="text-muted">История пока отсутствует.</div>@endforelse</div></div></div></div>
</div></div>
@endsection
