<?php

return [
    'title' => 'استكمال تسجيل الطالب', 'documents_link' => 'مستندات الطالب', 'save' => 'حفظ البيانات', 'not_provided' => 'غير محدد', 'optional' => 'اختياري', 'yes' => 'نعم', 'no' => 'لا', 'unknown' => 'غير محدد',
    'sections' => ['readiness' => 'جاهزية الملف الشخصي', 'personal' => 'البيانات الشخصية', 'representatives' => 'الوالدان والممثلون القانونيون', 'emergency' => 'جهات اتصال الطوارئ', 'enrollment' => 'القيد والتعليم', 'needs' => 'الاحتياجات التعليمية الخاصة', 'documents' => 'المستندات', 'finance' => 'المالية', 'completion' => 'استكمال التسجيل'],
    'readiness' => ['student' => 'بيانات الطالب', 'documents' => 'المستندات', 'enrollment' => 'القيد', 'overall' => 'الجاهزية العامة', 'blocking' => 'بيانات أو مستندات ناقصة', 'items' => ['name' => 'الاسم الأول واسم العائلة', 'birth_date' => 'تاريخ الميلاد', 'gender' => 'الجنس', 'citizenship' => 'الجنسية', 'residential_address' => 'عنوان السكن', 'phone' => 'الهاتف', 'contact' => 'ممثل أو جهة اتصال طوارئ', 'academic_year' => 'العام الدراسي', 'stage' => 'المرحلة', 'grade' => 'الصف', 'class' => 'الفصل', 'enrollment_date' => 'تاريخ القيد'], 'document_items' => ['photo' => 'صورة الطالب', 'birth_certificate' => 'شهادة الميلاد', 'identity' => 'جواز السفر أو تصريح الإقامة', 'previous_school' => 'وثيقة المدرسة السابقة', 'medical' => 'وثيقة طبية']],
    'fields' => ['last_name' => 'اسم العائلة', 'first_name' => 'الاسم الأول', 'patronymic' => 'اسم الأب', 'gender' => 'الجنس', 'male' => 'ذكر', 'female' => 'أنثى', 'birth_date' => 'تاريخ الميلاد', 'birth_place' => 'مكان الميلاد', 'citizenship' => 'الجنسية', 'citizenship_code' => 'رمز الدولة', 'phone' => 'الهاتف', 'email' => 'البريد الإلكتروني', 'residential_address' => 'عنوان السكن', 'registration_address' => 'عنوان التسجيل', 'photo' => 'صورة الطالب', 'snils' => 'SNILS', 'inn' => 'INN', 'relationship' => 'صلة القرابة', 'full_name' => 'الاسم الكامل', 'primary_contact' => 'جهة الاتصال الرئيسية', 'legal_representative' => 'ممثل قانوني', 'guardianship' => 'صلاحية الوصاية', 'address' => 'العنوان', 'notes' => 'ملاحظات', 'priority' => 'الأولوية', 'admission_context' => 'سياق القيد', 'previous_school' => 'المدرسة السابقة', 'previous_country' => 'دولة المدرسة السابقة', 'previous_grade' => 'الصف السابق', 'previous_class' => 'الفصل السابق', 'previous_notes' => 'ملاحظات التعليم السابق', 'has_ovz' => 'احتياجات تعليمية خاصة (OVZ)', 'has_disability' => 'إعاقة', 'requires_adapted_program' => 'يتطلب برنامجاً مكيفاً', 'requires_special_conditions' => 'يتطلب شروطاً خاصة', 'special_conditions' => 'الشروط الخاصة', 'consent_status' => 'حالة الموافقة', 'consent_date' => 'تاريخ الموافقة'],
    'relationships' => ['father' => 'الأب', 'mother' => 'الأم', 'guardian' => 'الوصي', 'custodian' => 'القيّم', 'other' => 'أخرى'], 'admission_contexts' => ['initial' => 'قيد أولي', 'transfer' => 'تحويل', 'continuation' => 'استمرار', 're_enrollment' => 'إعادة قيد', 'other' => 'أخرى'],
    'add_representative' => 'إضافة ممثل', 'add_emergency' => 'إضافة جهة اتصال', 'enrollment_missing' => 'لا يوجد قيد حالي.', 'finance_note' => 'البيانات المالية للعرض فقط ولا تؤثر في جاهزية الملف.', 'documents_note' => 'تبقى المستندات في المستودع المحمي الحالي.', 'submit_review' => 'إرسال للمراجعة', 'complete' => 'استكمال التسجيل', 'photo_help' => 'بحد أقصى 2 ميجابايت. JPG أو JPEG أو PNG أو WEBP.', 'identifiers_help' => 'SNILS وINN اختياريان في المرحلة الأولى وتُفحص خانة التحقق عند إدخالهما.', 'registration_statuses' => ['draft' => 'مسودة', 'data_incomplete' => 'البيانات ناقصة', 'documents_incomplete' => 'المستندات ناقصة', 'ready_for_review' => 'جاهز للمراجعة', 'completed' => 'مكتمل'],
    'documents' => ['other' => 'مستند آخر', 'type' => 'نوع المستند', 'files' => 'الملفات', 'series' => 'السلسلة', 'number' => 'الرقم', 'issued_by' => 'جهة الإصدار', 'subdivision_code' => 'رمز القسم', 'issuing_country' => 'دولة الإصدار', 'issue_date' => 'تاريخ الإصدار', 'expiry_date' => 'تاريخ الانتهاء', 'representative' => 'الممثل', 'enrollment' => 'القيد'],
    'validation' => ['snils' => 'أدخل رقم SNILS صحيحاً من 11 رقماً مع خانة تحقق صحيحة.', 'inn' => 'أدخل رقم INN صحيحاً من 10 أو 12 رقماً مع خانة تحقق صحيحة.', 'documents' => ['files_required' => 'اختر ملفاً واحداً على الأقل.', 'file_mimetypes' => 'يُسمح فقط بملفات PDF وJPG وJPEG وPNG وWEBP.', 'file_max' => 'يجب ألا يتجاوز حجم كل ملف 2 ميجابايت.', 'type_required' => 'اختر نوع المستند.', 'expiry_after_issue' => 'لا يجوز أن يكون تاريخ الانتهاء أسبق من تاريخ الإصدار.'], 'registration' => ['incomplete' => 'تنقص بيانات أو مستندات إلزامية للطالب.', 'not_ready' => 'التسجيل غير جاهز للاستكمال.']],
    'responses' => ['saved' => 'تم حفظ بيانات الطالب.', 'submitted' => 'تم إرسال الملف الشخصي للمراجعة.', 'completed' => 'تم استكمال تسجيل الطالب.'],
];
