@extends('layouts.dashboard')
@section('content')
<div class="container-fluid py-4"><div class="card border-0 shadow-sm mb-4"><div class="card-body d-flex flex-column flex-md-row gap-3 align-items-md-center"><div class="rounded-circle bg-light border d-flex align-items-center justify-content-center fs-3" style="width:80px;height:80px">{{ mb_substr($student->full_name,0,1) }}</div><div class="flex-grow-1"><h1 class="h3 mb-1">Финансы ученика</h1><div class="fw-bold">{{ $student->full_name }}</div><div class="text-muted">{{ $student->currentEnrollment?->schoolClass?->name ?: 'Класс не указан' }} · {{ $student->currentEnrollment?->academicYear?->name ?: 'Учебный год не указан' }} · {{ $student->statusLabel() }}</div></div>@can('manage invoices')<a class="btn btn-primary" href="{{ route('dashboard.students.invoices.create',$student) }}">Создать счёт</a>@endcan</div></div>
<div class="row g-3 mb-4">@foreach(['Начислено'=>'invoiced','Оплачено'=>'paid','Остаток'=>'remaining','Просрочено'=>'overdue'] as $label=>$key)<div class="col-6 col-lg-3"><div class="card border-0 shadow-sm"><div class="card-body"><div class="small text-muted">{{ $label }}</div><strong>{{ number_format((float)$summary[$key],2,'.',' ') }} EGP</strong></div></div></div>@endforeach</div>
@include('dashboard.finance.installments.student-timeline')
<ul class="nav nav-tabs mb-3"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#accounts">Счета</button></li><li class="nav-item"><a class="nav-link" href="#installment-timeline">Рассрочка</a></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#payments">Платежи</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#services">Услуги</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#history">История</button></li></ul><div class="tab-content">
<div id="accounts" class="tab-pane fade show active"><div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Номер</th><th>Дата</th><th>Срок</th><th>Учебный год</th><th>Итого</th><th>Оплачено</th><th>Остаток</th><th>Статус</th><th></th></tr></thead><tbody>@forelse($summary['invoices'] as $invoice)<tr><td>{{ $invoice->display_number }}</td><td>{{ $invoice->created_at?->format('d.m.Y') }}</td><td>{{ $invoice->due_date?->format('d.m.Y') ?: '—' }}</td><td>{{ $invoice->academicYear?->name }}</td><td>{{ $invoice->total_amount }} EGP</td><td>{{ $invoice->paid_amount }} EGP</td><td>{{ $invoice->remaining_amount }} EGP</td><td>{{ ['unpaid'=>'Не оплачен','partial'=>'Частично оплачен','paid'=>'Оплачен'][$invoice->status]??$invoice->status }} @if($invoice->due_date?->isPast() && bccomp($invoice->remaining_amount,'0',2)>0)<span class="badge bg-danger">Просрочено</span>@endif</td><td><a href="{{ route('dashboard.invoices.show',$invoice) }}">Открыть</a> @can('manage invoices')@if($invoice->status!=='paid')<a href="{{ route('dashboard.invoices.payments.create',$invoice) }}">Принять оплату</a>@endif @endcan</td></tr>@empty<tr><td colspan="9">Счета отсутствуют.</td></tr>@endforelse</tbody></table></div></div></div>
<div id="payments" class="tab-pane fade"><div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Номер</th><th>Дата</th><th>Счёт</th><th>Сумма</th><th>Способ</th><th>Касса</th><th></th></tr></thead><tbody>@forelse($summary['payments'] as $payment)<tr><td>{{ $payment->payment_number }}</td><td>{{ ($payment->paid_at??$payment->created_at)?->format('d.m.Y H:i') }}</td><td>{{ $payment->invoice?->display_number }}</td><td>{{ $payment->amount }} EGP</td><td>{{ ['cash'=>'Наличные','card'=>'Банковская карта','bank'=>'Банковский перевод'][$payment->payment_method]??$payment->payment_method }}</td><td>{{ $payment->cashAccount?->name }}</td><td><a href="{{ route('dashboard.payments.receipt',$payment) }}">Квитанция</a></td></tr>@empty<tr><td colspan="7">Платежи отсутствуют.</td></tr>@endforelse</tbody></table></div></div></div>
<div id="services" class="tab-pane fade"><div class="row g-3">@forelse($subscriptions as $subscription)<div class="col-md-6"><div class="card border-0 shadow-sm"><div class="card-body"><strong>{{ $subscription->fee?->name_ru }}</strong><div>{{ ['active'=>'Активна','suspended'=>'Приостановлена','cancelled'=>'Отменена','completed'=>'Завершена'][$subscription->status]??$subscription->status }}</div><div class="small text-muted">{{ $subscription->start_date?->format('d.m.Y') }} — {{ $subscription->end_date?->format('d.m.Y') ?: 'без окончания' }}</div><div>{{ $subscription->negotiated_price ?: $subscription->invoiceItems->sortByDesc('id')->first()?->unit_price ?: '—' }} EGP</div>@foreach(($subscription->metadata??[]) as $key=>$value)<span class="badge bg-light text-dark">{{ $value }}</span>@endforeach</div></div></div>@empty<div>Услуги отсутствуют.</div>@endforelse</div></div>
<div id="history" class="tab-pane fade"><div class="card border-0 shadow-sm"><div class="list-group list-group-flush">@forelse($history as $event)<div class="list-group-item"><strong>{{ $event['label'] }}</strong> · {{ $event['text'] }}<span class="float-end text-muted">{{ $event['at']?->format('d.m.Y H:i') }}</span></div>@empty<div class="p-3">История отсутствует.</div>@endforelse</div></div></div></div></div>
@endsection
