@extends('layouts.dashboard')
@section('content')
<div class="container py-4"><h1 class="h3 mb-4">Принять оплату</h1>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Счёт {{ $invoice->display_number }}</h2><div>{{ $invoice->student?->full_name }}</div><div class="row g-2 mt-3"><div class="col-md-4">Итого: <strong>{{ $invoice->total_amount }} EGP</strong></div><div class="col-md-4">Оплачено: <strong>{{ $invoice->paid_amount }} EGP</strong></div><div class="col-md-4">Остаток: <strong>{{ $invoice->remaining_amount }} EGP</strong></div></div></div></div>
<form method="POST" action="{{ route('dashboard.invoices.payments.store',$invoice) }}" class="card border-0 shadow-sm"><div class="card-body row g-3">@csrf<input type="hidden" name="idempotency_key" value="{{ $idempotencyKey }}">
@if($invoice->installments->isNotEmpty())<div class="col-12"><label class="form-label">Этап рассрочки</label><select name="invoice_installment_id" id="installment" class="form-select" required>@foreach($invoice->installments as $installment)<option value="{{ $installment->id }}" data-remaining="{{ $installment->remaining_amount }}" @selected(old('invoice_installment_id')==$installment->id)>{{ $installment->name_ru }} · до {{ $installment->due_date->format('d.m.Y') }} · остаток {{ $installment->remaining_amount }} EGP</option>@endforeach</select></div>@endif
<div class="col-md-4"><label class="form-label">Сумма, EGP</label><input id="payment-amount" type="number" step="0.01" min="0.01" max="{{ $invoice->installments->first()?->remaining_amount ?? $invoice->remaining_amount }}" name="amount" value="{{ old('amount',$invoice->installments->first()?->remaining_amount ?? $invoice->remaining_amount) }}" class="form-control" required></div>
<div class="col-md-4"><label class="form-label">Способ оплаты</label><select name="payment_method" class="form-select" required><option value="cash">Наличные</option><option value="card">Банковская карта</option><option value="bank">Банковский перевод</option></select></div>
<div class="col-md-4"><label class="form-label">Касса</label><select name="cash_account_id" class="form-select" required><option value="">Выберите кассу</option>@foreach($cashAccounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select></div>
<div class="col-12"><label class="form-label">Примечание</label><textarea name="notes" class="form-control">{{ old('notes') }}</textarea></div><div class="col-12"><div class="small text-muted mb-3">Дата и время платежа фиксируются системой при проведении.</div><button class="btn btn-success">Принять оплату</button></div></div></form></div>
@if($invoice->installments->isNotEmpty())<script>document.getElementById('installment').addEventListener('change',event=>{const amount=document.getElementById('payment-amount'),remaining=event.target.selectedOptions[0].dataset.remaining;amount.max=remaining;amount.value=remaining;});</script>@endif
@endsection
