<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><style>body{font-family:DejaVu Sans,sans-serif;font-size:12px;color:#111827}.box{border:1px solid #aaa;padding:10px;margin:10px 0}.amount{font-size:22px;font-weight:bold}.notice{background:#fff8db;font-weight:bold}.assets{text-align:center}.assets img{max-height:80px;max-width:170px;margin:14px;object-fit:contain}</style></head><body>
@include('pdf.partials.document-header',['documentTitle'=>'КВИТАНЦИЯ ОБ ОПЛАТЕ'])
<div class="box"><strong>{{ $payment->payment_number }}</strong> · {{ ($payment->paid_at??$payment->created_at)?->format('d.m.Y H:i') }}<br>Ученик: {{ $invoice->student?->full_name }} (ID {{ $invoice->student_id }})<br>Счёт: {{ $invoice->display_number }} · {{ $invoice->academicYear?->name }}</div>
<div class="box"><div class="amount">{{ $payment->amount }} EGP</div>Способ оплаты: {{ $methodLabels[$payment->payment_method]??$payment->payment_method }}<br>Касса: {{ $payment->cashAccount?->name }}<br>Итого по счёту: {{ $invoice->total_amount }} EGP<br>Оплачено ранее: {{ $previouslyPaid }} EGP<br>Этот платёж: {{ $payment->amount }} EGP<br>Остаток после платежа: {{ $remainingAfter }} EGP<br>Примечание: {{ $payment->notes ?: '—' }}<br>Кассир: {{ $payment->creator?->name ?: 'Не указан' }}</div>
@if($invoice->items->contains('is_non_refundable', true))<div class="box notice">Регистрационный взнос возврату не подлежит.</div>@endif
<div class="assets">@foreach([['path'=>$settings->stamp_path,'alt'=>'Официальная печать школы'],['path'=>$settings->director_signature_path,'alt'=>'Подпись директора']] as $asset)@if($asset['path'] && Storage::disk('public')->exists($asset['path']))<img src="data:{{ Storage::disk('public')->mimeType($asset['path']) }};base64,{{ base64_encode(Storage::disk('public')->get($asset['path'])) }}" alt="{{ $asset['alt'] }}">@endif @endforeach</div>
@include('pdf.partials.document-footer',['academicYear'=>$invoice->academicYear])
</body></html>
