<!doctype html>
<html lang="ru">
<head><meta charset="utf-8"><title>Квитанция об оплате</title><style>body{font-family:DejaVu Sans,Arial,sans-serif;color:#111827;margin:28px}.receipt{max-width:850px;margin:auto}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.box{border:1px solid #d1d5db;padding:12px}.amount{font-size:24px;font-weight:bold}.assets img{max-height:90px;max-width:180px;object-fit:contain;margin:16px}@media print{.actions{display:none}}</style></head>
<body><div class="receipt">
<div class="actions"><button onclick="window.print()">Печать</button> <a href="{{ route('dashboard.payments.receipt.pdf',$payment) }}">Скачать PDF</a></div>
<x-school-document-header title="КВИТАНЦИЯ ОБ ОПЛАТЕ" :academic-year="$invoice->academicYear?->name" />
<div class="grid"><div class="box">Номер квитанции<br><strong>{{ $payment->payment_number }}</strong></div><div class="box">Дата платежа<br><strong>{{ ($payment->paid_at??$payment->created_at)?->format('d.m.Y H:i') }}</strong></div><div class="box">Ученик<br><strong>{{ $invoice->student?->full_name }}</strong><br>ID {{ $invoice->student_id }}</div><div class="box">Счёт<br><strong>{{ $invoice->display_number }}</strong><br>{{ $invoice->academicYear?->name }}</div></div>
<div class="box" style="margin-top:16px"><div class="amount">{{ $payment->amount }} EGP</div><p>Способ оплаты: {{ $methodLabels[$payment->payment_method]??$payment->payment_method }}</p><p>Касса: {{ $payment->cashAccount?->name }}</p><p>Итого по счёту: {{ $invoice->total_amount }} EGP</p><p>Оплачено ранее: {{ $previouslyPaid }} EGP</p><p>Этот платёж: {{ $payment->amount }} EGP</p><p>Остаток после платежа: {{ $remainingAfter }} EGP</p>@if($payment->notes)<p>Примечание: {{ $payment->notes }}</p>@endif<p>Кассир: {{ $payment->creator?->name ?: 'Не указан' }}</p></div>
@if($payment->installment)<div class="box" style="margin-top:16px"><strong>Этап рассрочки:</strong> {{ $payment->installment->name_ru }}<br>Остаток по этапу после платежа: {{ $payment->installment->remaining_amount }} EGP</div>@endif
@if($invoice->items->contains('is_non_refundable', true))<div class="box" style="margin-top:16px;background:#fff8db;font-weight:bold;">Регистрационный взнос возврату не подлежит.</div>@endif
<div class="assets">@if($settings->stampAsset())<img src="{{ $settings->stampAsset()['data_uri'] }}" alt="Официальная печать школы">@endif @if($settings->directorSignatureAsset())<img src="{{ $settings->directorSignatureAsset()['data_uri'] }}" alt="Подпись директора">@endif</div>
@include('pdf.partials.document-footer',['academicYear'=>$invoice->academicYear])
</div></body></html>
