<?php

namespace Tests\Feature\Teacher;

use App\Filament\Teacher\Pages\TeacherAttendance;
use App\Models\Attendance;
use App\Models\Enrollment;
use App\Models\Grade;
use App\Models\SchoolClass;
use App\Models\Stage;
use App\Models\Student;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Livewire\Livewire;
use Tests\TestCase;

class TeacherAttendanceTest extends TestCase
{
    use RefreshDatabase;

    protected function makeEnrollment(string $studentName = 'Test Student'): Enrollment
    {
        $stage = Stage::create(['name' => 'Primary']);
        $grade = Grade::create(['name' => 'Grade 1', 'stage_id' => $stage->id]);
        $class = SchoolClass::create([
            'grade_id' => $grade->id,
            'code' => 'A',
            'name_ar' => 'فصل A',
            'name_ru' => 'Класс A',
        ]);
        $student = Student::create(['name' => $studentName]);

        return Enrollment::create([
            'student_id' => $student->id,
            'stage_id' => $stage->id,
            'grade_id' => $grade->id,
            'class_id' => $class->id,
            'status' => 'active',
        ]);
    }

    /**
     * Regression test: TeacherAttendance::saveAttendance() previously wrote
     * to attendances.student_id, a column that does not exist. attendances
     * is keyed via enrollment_id.
     */
    public function test_attendance_can_be_saved_for_a_single_student(): void
    {
        $user = User::factory()->create();
        $enrollment = $this->makeEnrollment();

        Livewire::actingAs($user)
            ->test(TeacherAttendance::class)
            ->set('classId', $enrollment->class_id)
            ->call('loadStudents')
            ->set("attendance.{$enrollment->id}", 'absent')
            ->call('saveAttendance')
            ->assertHasNoErrors();

        $this->assertDatabaseHas('attendances', [
            'enrollment_id' => $enrollment->id,
            'status' => 'absent',
            'type' => 'daily',
        ]);
    }

    public function test_attendance_can_be_saved_for_multiple_students(): void
    {
        $user = User::factory()->create();
        $stage = Stage::create(['name' => 'Primary']);
        $grade = Grade::create(['name' => 'Grade 1', 'stage_id' => $stage->id]);
        $class = SchoolClass::create([
            'grade_id' => $grade->id,
            'code' => 'A',
            'name_ar' => 'فصل A',
            'name_ru' => 'Класс A',
        ]);

        $studentA = Student::create(['name' => 'Student A']);
        $studentB = Student::create(['name' => 'Student B']);

        $enrollmentA = Enrollment::create([
            'student_id' => $studentA->id, 'stage_id' => $stage->id,
            'grade_id' => $grade->id, 'class_id' => $class->id, 'status' => 'active',
        ]);
        $enrollmentB = Enrollment::create([
            'student_id' => $studentB->id, 'stage_id' => $stage->id,
            'grade_id' => $grade->id, 'class_id' => $class->id, 'status' => 'active',
        ]);

        Livewire::actingAs($user)
            ->test(TeacherAttendance::class)
            ->set('classId', $class->id)
            ->call('loadStudents')
            ->set("attendance.{$enrollmentA->id}", 'present')
            ->set("attendance.{$enrollmentB->id}", 'late')
            ->call('saveAttendance')
            ->assertHasNoErrors();

        $this->assertDatabaseHas('attendances', ['enrollment_id' => $enrollmentA->id, 'status' => 'present']);
        $this->assertDatabaseHas('attendances', ['enrollment_id' => $enrollmentB->id, 'status' => 'late']);
    }

    /**
     * Regression test: attendance_key is NOT NULL/unique with no default
     * and was never generated by the teacher panel before this fix.
     */
    public function test_attendance_key_is_generated_correctly(): void
    {
        $user = User::factory()->create();
        $enrollment = $this->makeEnrollment();
        $today = now()->toDateString();

        Livewire::actingAs($user)
            ->test(TeacherAttendance::class)
            ->set('classId', $enrollment->class_id)
            ->call('loadStudents')
            ->set("attendance.{$enrollment->id}", 'present')
            ->call('saveAttendance');

        $this->assertDatabaseHas('attendances', [
            'attendance_key' => Attendance::buildAttendanceKey('daily', $enrollment->id, $today),
        ]);
    }

    public function test_saving_twice_updates_rather_than_duplicates(): void
    {
        $user = User::factory()->create();
        $enrollment = $this->makeEnrollment();

        $component = Livewire::actingAs($user)
            ->test(TeacherAttendance::class)
            ->set('classId', $enrollment->class_id)
            ->call('loadStudents');

        $component->set("attendance.{$enrollment->id}", 'present')->call('saveAttendance');
        $component->set("attendance.{$enrollment->id}", 'late')->call('saveAttendance');

        $this->assertSame(1, Attendance::where('enrollment_id', $enrollment->id)->count());
        $this->assertDatabaseHas('attendances', ['enrollment_id' => $enrollment->id, 'status' => 'late']);
    }

    /**
     * All statuses the dashboard workflow supports, including the
     * previously-missing "excused" option, must be persistable via the
     * teacher panel too.
     */
    public function test_all_supported_statuses_can_be_saved(): void
    {
        $user = User::factory()->create();

        foreach (['present', 'absent', 'late', 'excused'] as $status) {
            $enrollment = $this->makeEnrollment("Student {$status}");

            Livewire::actingAs($user)
                ->test(TeacherAttendance::class)
                ->set('classId', $enrollment->class_id)
                ->call('loadStudents')
                ->set("attendance.{$enrollment->id}", $status)
                ->call('saveAttendance')
                ->assertHasNoErrors();

            $this->assertDatabaseHas('attendances', [
                'enrollment_id' => $enrollment->id,
                'status' => $status,
            ]);
        }
    }
}
