@extends('layouts.dashboard')
@section('content')
@php $statusLabels=['unpaid'=>'Не оплачен','partial'=>'Частично оплачен','paid'=>'Оплачен','cancelled'=>__('invoices.invoice_cancelled')]; $methodLabels=['cash'=>'Наличные','card'=>'Банковская карта','bank'=>'Банковский перевод']; @endphp
<div class="container-fluid py-4"><div class="d-flex flex-column flex-lg-row justify-content-between gap-3 mb-4"><div><h1 class="h3 mb-1">Счёт {{ $invoice->display_number }}</h1><div class="text-muted">{{ $invoice->student?->full_name ?: $invoice->customer_name }}</div></div><div class="d-flex flex-wrap gap-2">@can('manage invoices')@if($invoice->status!=='paid')<a class="btn btn-success" href="{{ route('dashboard.invoices.payments.create',$invoice) }}">Принять оплату</a>@endif @endcan<a class="btn btn-outline-secondary" href="{{ route('dashboard.invoices.print',$invoice) }}" target="_blank">Печать счёта</a><a class="btn btn-outline-danger" id="invoice-pdf" href="{{ route('dashboard.invoices.pdf',$invoice) }}">{{ __('finance_uat.download_pdf') }}</a><button type="button" class="btn btn-outline-success" id="share-invoice">{{ __('finance_uat.share') }}</button>@if($shareRecipient)<a class="btn btn-outline-success" id="invoice-whatsapp" href="{{ \App\Support\FinanceShareRecipient::whatsappUrl($shareRecipient, __('finance_uat.whatsapp_invoice_message',['number'=>$invoice->display_number,'amount'=>number_format((float)$invoice->total_amount,2,'.','')])) }}" target="_blank" rel="noopener noreferrer">{{ __('finance_uat.send_whatsapp') }}</a>@else<button type="button" class="btn btn-outline-secondary" disabled title="{{ __('finance_uat.phone_missing') }}">{{ __('finance_uat.phone_missing') }}</button>@endif @if($invoice->student)<a class="btn btn-outline-primary" href="{{ route('dashboard.students.finance',$invoice->student) }}">{{ __('finance_uat.student_account') }}</a>@endif</div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body row g-3"><div class="col-md-3"><span class="text-muted">Номер</span><div>{{ $invoice->display_number }}</div></div><div class="col-md-3"><span class="text-muted">Учебный год</span><div>{{ $invoice->academicYear?->name ?: '—' }}</div></div><div class="col-md-3"><span class="text-muted">Статус</span><div>{{ $statusLabels[$invoice->status]??$invoice->status }}</div></div><div class="col-md-3"><span class="text-muted">Валюта</span><div>EGP</div></div><div class="col-md-3"><span class="text-muted">Дата выставления</span><div>{{ $invoice->created_at?->format('d.m.Y H:i') }}</div></div><div class="col-md-3"><span class="text-muted">Срок оплаты</span><div>{{ $invoice->due_date?->format('d.m.Y') ?: '—' }}</div></div></div></div>
<div class="row g-3 mb-4">@foreach(['Итого'=>'total_amount','Оплачено'=>'paid_amount','Остаток'=>'remaining_amount'] as $label=>$field)<div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><div class="text-muted">{{ $label }}</div><strong class="fs-4">{{ number_format((float)$invoice->{$field},2,'.',' ') }} EGP</strong></div></div></div>@endforeach</div>
@if($invoice->items->contains('is_non_refundable', true))<div class="alert alert-warning fw-semibold">Регистрационный взнос возврату не подлежит.</div>@endif
@if($invoice->isCancelled())
<div class="alert alert-danger"><strong>{{ __('invoices.invoice_cancelled') }}</strong>
@if($invoice->cancellation_reason) — {{ $invoice->cancellation_reason }}@endif
<div class="small text-muted mt-1">{{ __('invoices.cancelled_by') }}: {{ $invoice->cancelledBy?->name ?: '—' }} · {{ __('invoices.cancelled_at') }}: {{ $invoice->cancelled_at?->format('d.m.Y H:i') ?: '—' }}</div>
</div>
@elseif(bccomp((string)$invoice->netPaidAmount(),'0.00',2) <= 0)
@can('void invoices')
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h6">{{ __('invoices.void_invoice') }}</h2>
<form method="POST" action="{{ route('dashboard.invoices.void',$invoice) }}" onsubmit="return confirm('{{ __('invoices.void_confirm') }}');" class="row g-2 align-items-end">@csrf
<div class="col-md-8"><label class="form-label small" for="void_reason">{{ __('invoices.void_reason') }} <span class="text-danger" aria-hidden="true">*</span></label><input type="text" name="reason" id="void_reason" maxlength="500" required class="form-control @error('reason') is-invalid @enderror">@error('reason')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
<div class="col-md-4"><button class="btn btn-outline-danger">{{ __('invoices.void_invoice') }}</button></div>
</form></div></div>
@endcan
@endif
@if($invoice->note)<div class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="text-muted">Примечание к счёту</div>{{ $invoice->note }}</div></div>@endif
@include('dashboard.finance.installments.invoice-timeline')
	<div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">{{ __('finance_uat.payment_purpose') }}</h2><p class="text-muted small">{{ __('finance_uat.purpose_explanation') }}</p><div class="table-responsive"><table class="table"><thead><tr><th>{{ __('finance_uat.service') }}</th><th>{{ __('finance_uat.description') }}</th><th>{{ __('finance_uat.variant') }}</th><th>{{ __('finance_uat.quantity') }}</th><th>{{ __('finance_uat.unit_price') }}</th><th>{{ __('finance_uat.amount') }}</th></tr></thead><tbody>@forelse($invoice->items as $item)<tr><td><strong>{{ $item->fee?->name_ru ?: $item->description }}</strong></td><td>{{ $item->description ?: '—' }}</td><td>{{ collect($item->metadata??[])->except(['pricing_date','tariff_valid_from','tariff_valid_to','grade_id','enrollment_mode_id'])->filter()->implode(' · ') ?: '—' }}</td><td>{{ $item->quantity ?: 1 }}</td><td>{{ $item->unit_price ?: $item->amount }} EGP</td><td>{{ $item->amount }} EGP</td></tr>@empty<tr><td colspan="6">{{ __('finance_uat.no_invoice_items') }}</td></tr>@endforelse</tbody></table></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">Платежи</h2><div class="table-responsive"><table class="table"><thead><tr><th>Номер</th><th>Дата</th><th>Сумма</th><th>Способ</th><th>Касса</th><th></th></tr></thead><tbody>@forelse($invoice->payments as $payment)<tr><td>{{ $payment->payment_number }}</td><td>{{ ($payment->paid_at??$payment->created_at)?->format('d.m.Y H:i') }}</td><td>{{ $payment->amount }} EGP</td><td>{{ $methodLabels[$payment->payment_method]??$payment->payment_method }}</td><td>{{ $payment->cashAccount?->name ?: '—' }}</td><td><a href="{{ route('dashboard.payments.receipt',$payment) }}">Квитанция</a>@if(bccomp((string)$payment->refundedAmount(),'0.00',2) > 0)<div class="small text-muted">{{ __('invoices.refunded') }}: {{ $payment->refundedAmount() }} EGP</div>@endif @can('refund payments')@if(bccomp((string)$payment->refundableAmount(),'0.00',2) > 0 && !$invoice->isCancelled())<div><a class="small" href="{{ route('dashboard.payments.refund.create',$payment) }}">{{ __('invoices.create_refund') }}</a></div>@endif @endcan</td></tr>@empty<tr><td colspan="6">Платежи отсутствуют.</td></tr>@endforelse</tbody></table></div></div></div></div>
<script>
document.getElementById('share-invoice')?.addEventListener('click', async () => {
    const pdfLink = document.getElementById('invoice-pdf');
    if (!navigator.share || !navigator.canShare) { window.location.assign(pdfLink.href); return; }
    try {
        const response = await fetch(pdfLink.href, { credentials: 'same-origin' });
        if (!response.ok) throw new Error('PDF download failed');
        const file = new File([await response.blob()], @json('invoice-'.$invoice->id.'.pdf'), { type: 'application/pdf' });
        if (!navigator.canShare({ files: [file] })) { window.location.assign(pdfLink.href); return; }
        await navigator.share({ title: @json('Счёт '.$invoice->display_number), files: [file] });
    } catch (error) { if (error.name !== 'AbortError') window.location.assign(pdfLink.href); }
});
</script>
@endsection
