@extends('layouts.dashboard')
@section('content')
@php $statusLabels=['unpaid'=>'Не оплачен','partial'=>'Частично оплачен','paid'=>'Оплачен']; $methodLabels=['cash'=>'Наличные','card'=>'Банковская карта','bank'=>'Банковский перевод']; @endphp
<div class="container-fluid py-4"><div class="d-flex flex-column flex-lg-row justify-content-between gap-3 mb-4"><div><h1 class="h3 mb-1">Счёт {{ $invoice->display_number }}</h1><div class="text-muted">{{ $invoice->student?->full_name ?: $invoice->customer_name }}</div></div><div class="d-flex flex-wrap gap-2">@can('manage invoices')@if($invoice->status!=='paid')<a class="btn btn-success" href="{{ route('dashboard.invoices.payments.create',$invoice) }}">Принять оплату</a>@endif @endcan<a class="btn btn-outline-secondary" href="{{ route('dashboard.invoices.print',$invoice) }}" target="_blank">Печать счёта</a>@if($invoice->student)<a class="btn btn-outline-primary" href="{{ route('dashboard.students.show',$invoice->student) }}">Открыть ученика</a><a class="btn btn-outline-primary" href="{{ route('dashboard.students.finance',$invoice->student) }}">Финансы ученика</a>@endif</div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body row g-3"><div class="col-md-3"><span class="text-muted">Номер</span><div>{{ $invoice->display_number }}</div></div><div class="col-md-3"><span class="text-muted">Учебный год</span><div>{{ $invoice->academicYear?->name ?: '—' }}</div></div><div class="col-md-3"><span class="text-muted">Статус</span><div>{{ $statusLabels[$invoice->status]??$invoice->status }}</div></div><div class="col-md-3"><span class="text-muted">Валюта</span><div>EGP</div></div><div class="col-md-3"><span class="text-muted">Дата выставления</span><div>{{ $invoice->created_at?->format('d.m.Y H:i') }}</div></div><div class="col-md-3"><span class="text-muted">Срок оплаты</span><div>{{ $invoice->due_date?->format('d.m.Y') ?: '—' }}</div></div></div></div>
<div class="row g-3 mb-4">@foreach(['Итого'=>'total_amount','Оплачено'=>'paid_amount','Остаток'=>'remaining_amount'] as $label=>$field)<div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><div class="text-muted">{{ $label }}</div><strong class="fs-4">{{ number_format((float)$invoice->{$field},2,'.',' ') }} EGP</strong></div></div></div>@endforeach</div>
@if($invoice->items->contains('is_non_refundable', true))<div class="alert alert-warning fw-semibold">Регистрационный взнос возврату не подлежит.</div>@endif
@if($invoice->note)<div class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="text-muted">Примечание к счёту</div>{{ $invoice->note }}</div></div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Услуги</h2><div class="table-responsive"><table class="table"><thead><tr><th>Услуга</th><th>Вариант</th><th>Количество</th><th>Цена</th><th>Сумма</th><th>Подписка</th></tr></thead><tbody>@forelse($invoice->items as $item)<tr><td>{{ $item->description }}</td><td>{{ collect($item->metadata??[])->filter()->implode(' · ') ?: '—' }}</td><td>{{ $item->quantity ?: 1 }}</td><td>{{ $item->unit_price ?: $item->amount }} EGP</td><td>{{ $item->amount }} EGP</td><td>{{ $item->subscription_id ? '#'.$item->subscription_id : '—' }}</td></tr>@empty<tr><td colspan="6">Позиции отсутствуют.</td></tr>@endforelse</tbody></table></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">Платежи</h2><div class="table-responsive"><table class="table"><thead><tr><th>Номер</th><th>Дата</th><th>Сумма</th><th>Способ</th><th>Касса</th><th></th></tr></thead><tbody>@forelse($invoice->payments as $payment)<tr><td>{{ $payment->payment_number }}</td><td>{{ ($payment->paid_at??$payment->created_at)?->format('d.m.Y H:i') }}</td><td>{{ $payment->amount }} EGP</td><td>{{ $methodLabels[$payment->payment_method]??$payment->payment_method }}</td><td>{{ $payment->cashAccount?->name ?: '—' }}</td><td><a href="{{ route('dashboard.payments.receipt',$payment) }}">Квитанция</a></td></tr>@empty<tr><td colspan="6">Платежи отсутствуют.</td></tr>@endforelse</tbody></table></div></div></div></div>
@endsection
