<?php

namespace Tests\Feature\Finance;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Schema;
use Tests\TestCase;

/**
 * Regression test for a MySQL portability bug in
 * 2026_09_02_100000_create_installment_coverage_periods_table: Laravel's
 * default auto-generated name for the composite unique index —
 * "installment_coverage_periods_invoice_installment_id_service_coverage_id_unique"
 * (78 characters) — exceeds MySQL's 64-character identifier limit. SQLite
 * (this suite's own test connection) never enforces that limit, so this
 * bug was invisible to the existing automated suite and only ever
 * surfaced when actually migrating a real MySQL database. This test does
 * not depend on a MySQL connection to catch a regression: it asserts the
 * structural invariant directly (the index's actual, driver-reported name
 * must stay short) regardless of which driver runs the migration — and it
 * locates the index by its columns, never by asserting one specific
 * replacement name, so a future legitimate rename would not break it.
 */
class InstallmentCoveragePeriodSchemaTest extends TestCase
{
    use RefreshDatabase;

    public function test_composite_unique_index_uses_a_short_explicit_name_not_the_overlong_default(): void
    {
        $indexes = collect(Schema::getIndexes('installment_coverage_periods'));

        $compositeUnique = $indexes->first(fn (array $index) => $index['unique']
            && $index['columns'] === ['invoice_installment_id', 'service_coverage_id']);

        $this->assertNotNull($compositeUnique, 'expected a unique index over (invoice_installment_id, service_coverage_id)');

        // MySQL's identifier limit — asserted directly, not merely trusted:
        // a future revert to Laravel's auto-generated default name would
        // fail this assertion under any driver, not only MySQL.
        $this->assertLessThanOrEqual(64, strlen($compositeUnique['name']),
            "index name '{$compositeUnique['name']}' exceeds MySQL's 64-character identifier limit");

        // Documents exactly what broke: Laravel's own default naming
        // convention for this exact column pair really does exceed the
        // limit, so an explicit short name is not optional cleanup.
        $autoGeneratedDefaultName = 'installment_coverage_periods_invoice_installment_id_service_coverage_id_unique';
        $this->assertGreaterThan(64, strlen($autoGeneratedDefaultName),
            'sanity check: this is what the auto-generated name would have been, and why it is unsafe on MySQL');
        $this->assertNotSame($autoGeneratedDefaultName, $compositeUnique['name']);
    }

    public function test_table_keeps_its_foreign_keys_and_supporting_indexes_unchanged(): void
    {
        $indexes = collect(Schema::getIndexes('installment_coverage_periods'));

        // invoice_installment_id has no explicit standalone ->index() call
        // in this migration (only its foreignId()-implied one) — on some
        // drivers that column-covering index is a dedicated single-column
        // one, on others it is only the leading column of the composite
        // unique. Either way is a genuinely covered FK column; asserting a
        // literal single-column index here would be a driver-specific
        // implementation detail, not the actual invariant.
        $this->assertTrue($indexes->contains(fn (array $index) => ($index['columns'][0] ?? null) === 'invoice_installment_id'));
        // service_coverage_id DOES have an explicit ->index() call in the
        // migration, so a dedicated single-column index for it must exist.
        $this->assertTrue($indexes->contains(fn (array $index) => $index['columns'] === ['service_coverage_id']));

        $foreignKeys = collect(Schema::getForeignKeys('installment_coverage_periods'));
        $this->assertTrue($foreignKeys->contains(fn (array $fk) => $fk['columns'] === ['invoice_installment_id'] && $fk['foreign_table'] === 'invoice_installments'));
        $this->assertTrue($foreignKeys->contains(fn (array $fk) => $fk['columns'] === ['service_coverage_id'] && $fk['foreign_table'] === 'service_coverages'));
    }
}
