<?php

namespace Tests\Feature\Finance;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Schema;
use Tests\TestCase;

/**
 * Regression test for a MySQL portability bug in
 * 2026_08_31_100000_create_payment_refund_allocations_table: Laravel's
 * default auto-generated name for the composite unique index —
 * "payment_refund_allocations_payment_refund_id_payment_allocation_id_unique"
 * (73 characters) — exceeds MySQL's 64-character identifier limit. SQLite
 * (this suite's own test connection) never enforces that limit, so this
 * bug was invisible to the existing automated suite and only ever
 * surfaced when actually migrating a real MySQL database. This test does
 * not depend on a MySQL connection to catch a regression: it asserts the
 * structural invariant directly (the index's actual, driver-reported name
 * must stay short) regardless of which driver runs the migration.
 */
class PaymentRefundAllocationSchemaTest extends TestCase
{
    use RefreshDatabase;

    public function test_composite_unique_index_uses_a_short_explicit_name_not_the_overlong_default(): void
    {
        $indexes = collect(Schema::getIndexes('payment_refund_allocations'));

        $compositeUnique = $indexes->first(fn (array $index) => $index['unique']
            && $index['columns'] === ['payment_refund_id', 'payment_allocation_id']);

        $this->assertNotNull($compositeUnique, 'expected a unique index over (payment_refund_id, payment_allocation_id)');

        // MySQL's identifier limit — asserted directly, not merely trusted:
        // a future revert to Laravel's auto-generated default name would
        // fail this assertion under any driver, not only MySQL.
        $this->assertLessThanOrEqual(64, strlen($compositeUnique['name']),
            "index name '{$compositeUnique['name']}' exceeds MySQL's 64-character identifier limit");

        // Documents exactly what broke: Laravel's own default naming
        // convention for this exact column pair really does exceed the
        // limit, so an explicit short name is not optional cleanup.
        $autoGeneratedDefaultName = 'payment_refund_allocations_payment_refund_id_payment_allocation_id_unique';
        $this->assertGreaterThan(64, strlen($autoGeneratedDefaultName),
            'sanity check: this is what the auto-generated name would have been, and why it is unsafe on MySQL');
        $this->assertNotSame($autoGeneratedDefaultName, $compositeUnique['name']);
    }

    public function test_table_keeps_its_two_foreign_keys_and_individual_indexes_unchanged(): void
    {
        $indexes = collect(Schema::getIndexes('payment_refund_allocations'));

        $this->assertTrue($indexes->contains(fn (array $index) => ! $index['unique'] && $index['columns'] === ['payment_refund_id']));
        $this->assertTrue($indexes->contains(fn (array $index) => ! $index['unique'] && $index['columns'] === ['payment_allocation_id']));

        $foreignKeys = collect(Schema::getForeignKeys('payment_refund_allocations'));
        $this->assertTrue($foreignKeys->contains(fn (array $fk) => $fk['columns'] === ['payment_refund_id'] && $fk['foreign_table'] === 'payment_refunds'));
        $this->assertTrue($foreignKeys->contains(fn (array $fk) => $fk['columns'] === ['payment_allocation_id'] && $fk['foreign_table'] === 'payment_allocations'));
    }
}
